# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_delineation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DelineationDialog(object):
    def setupUi(self, DelineationDialog):
        DelineationDialog.setObjectName("DelineationDialog")
        DelineationDialog.resize(549, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DelineationDialog.sizePolicy().hasHeightForWidth())
        DelineationDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/swatplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DelineationDialog.setWindowIcon(icon)
        DelineationDialog.setSizeGripEnabled(False)
        self.gridLayout_14 = QtWidgets.QGridLayout(DelineationDialog)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.demGroup = QtWidgets.QGroupBox(DelineationDialog)
        self.demGroup.setObjectName("demGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.demGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.selectDemButton = QtWidgets.QPushButton(self.demGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDemButton.sizePolicy().hasHeightForWidth())
        self.selectDemButton.setSizePolicy(sizePolicy)
        self.selectDemButton.setObjectName("selectDemButton")
        self.gridLayout.addWidget(self.selectDemButton, 0, 1, 1, 1)
        self.selectDem = QtWidgets.QLineEdit(self.demGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDem.sizePolicy().hasHeightForWidth())
        self.selectDem.setSizePolicy(sizePolicy)
        self.selectDem.setObjectName("selectDem")
        self.gridLayout.addWidget(self.selectDem, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.demGroup, 0, 0, 1, 5)
        self.tabWidget = QtWidgets.QTabWidget(DelineationDialog)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.delinTab = QtWidgets.QWidget()
        self.delinTab.setObjectName("delinTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.delinTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.thresholdWidget = QtWidgets.QWidget(self.delinTab)
        self.thresholdWidget.setObjectName("thresholdWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.thresholdWidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.thresholdLabelCh = QtWidgets.QLabel(self.thresholdWidget)
        self.thresholdLabelCh.setObjectName("thresholdLabelCh")
        self.gridLayout_10.addWidget(self.thresholdLabelCh, 0, 0, 1, 1)
        self.numCellsCh = QtWidgets.QLineEdit(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numCellsCh.sizePolicy().hasHeightForWidth())
        self.numCellsCh.setSizePolicy(sizePolicy)
        self.numCellsCh.setMinimumSize(QtCore.QSize(50, 20))
        self.numCellsCh.setObjectName("numCellsCh")
        self.gridLayout_10.addWidget(self.numCellsCh, 0, 1, 1, 1)
        self.numCellsLabelCh = QtWidgets.QLabel(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numCellsLabelCh.sizePolicy().hasHeightForWidth())
        self.numCellsLabelCh.setSizePolicy(sizePolicy)
        self.numCellsLabelCh.setObjectName("numCellsLabelCh")
        self.gridLayout_10.addWidget(self.numCellsLabelCh, 0, 2, 1, 1)
        self.areaCh = QtWidgets.QLineEdit(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaCh.sizePolicy().hasHeightForWidth())
        self.areaCh.setSizePolicy(sizePolicy)
        self.areaCh.setMinimumSize(QtCore.QSize(50, 20))
        self.areaCh.setObjectName("areaCh")
        self.gridLayout_10.addWidget(self.areaCh, 0, 3, 1, 1)
        self.areaLabelCh = QtWidgets.QLabel(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaLabelCh.sizePolicy().hasHeightForWidth())
        self.areaLabelCh.setSizePolicy(sizePolicy)
        self.areaLabelCh.setObjectName("areaLabelCh")
        self.gridLayout_10.addWidget(self.areaLabelCh, 0, 4, 1, 1)
        self.areaUnitsBox = QtWidgets.QComboBox(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaUnitsBox.sizePolicy().hasHeightForWidth())
        self.areaUnitsBox.setSizePolicy(sizePolicy)
        self.areaUnitsBox.setObjectName("areaUnitsBox")
        self.gridLayout_10.addWidget(self.areaUnitsBox, 0, 5, 2, 1)
        self.thresholdLabelSt = QtWidgets.QLabel(self.thresholdWidget)
        self.thresholdLabelSt.setObjectName("thresholdLabelSt")
        self.gridLayout_10.addWidget(self.thresholdLabelSt, 1, 0, 1, 1)
        self.numCellsSt = QtWidgets.QLineEdit(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numCellsSt.sizePolicy().hasHeightForWidth())
        self.numCellsSt.setSizePolicy(sizePolicy)
        self.numCellsSt.setMinimumSize(QtCore.QSize(50, 20))
        self.numCellsSt.setObjectName("numCellsSt")
        self.gridLayout_10.addWidget(self.numCellsSt, 1, 1, 1, 1)
        self.numCellsLabelSt = QtWidgets.QLabel(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numCellsLabelSt.sizePolicy().hasHeightForWidth())
        self.numCellsLabelSt.setSizePolicy(sizePolicy)
        self.numCellsLabelSt.setObjectName("numCellsLabelSt")
        self.gridLayout_10.addWidget(self.numCellsLabelSt, 1, 2, 1, 1)
        self.areaSt = QtWidgets.QLineEdit(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaSt.sizePolicy().hasHeightForWidth())
        self.areaSt.setSizePolicy(sizePolicy)
        self.areaSt.setMinimumSize(QtCore.QSize(50, 20))
        self.areaSt.setObjectName("areaSt")
        self.gridLayout_10.addWidget(self.areaSt, 1, 3, 1, 1)
        self.areaLabelSt = QtWidgets.QLabel(self.thresholdWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaLabelSt.sizePolicy().hasHeightForWidth())
        self.areaLabelSt.setSizePolicy(sizePolicy)
        self.areaLabelSt.setObjectName("areaLabelSt")
        self.gridLayout_10.addWidget(self.areaLabelSt, 1, 4, 1, 1)
        self.gridLayout_4.addWidget(self.thresholdWidget, 2, 0, 1, 4)
        self.checkBurn = QtWidgets.QCheckBox(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBurn.sizePolicy().hasHeightForWidth())
        self.checkBurn.setSizePolicy(sizePolicy)
        self.checkBurn.setObjectName("checkBurn")
        self.gridLayout_4.addWidget(self.checkBurn, 0, 0, 1, 3)
        self.delinRunButton1 = QtWidgets.QPushButton(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delinRunButton1.sizePolicy().hasHeightForWidth())
        self.delinRunButton1.setSizePolicy(sizePolicy)
        self.delinRunButton1.setObjectName("delinRunButton1")
        self.gridLayout_4.addWidget(self.delinRunButton1, 2, 4, 1, 2)
        self.useOutlets = QtWidgets.QCheckBox(self.delinTab)
        self.useOutlets.setChecked(True)
        self.useOutlets.setObjectName("useOutlets")
        self.gridLayout_4.addWidget(self.useOutlets, 3, 0, 1, 3)
        self.delinRunButton2 = QtWidgets.QPushButton(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delinRunButton2.sizePolicy().hasHeightForWidth())
        self.delinRunButton2.setSizePolicy(sizePolicy)
        self.delinRunButton2.setMinimumSize(QtCore.QSize(120, 0))
        self.delinRunButton2.setObjectName("delinRunButton2")
        self.gridLayout_4.addWidget(self.delinRunButton2, 6, 4, 1, 2)
        self.selectOutlets = QtWidgets.QLineEdit(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectOutlets.sizePolicy().hasHeightForWidth())
        self.selectOutlets.setSizePolicy(sizePolicy)
        self.selectOutlets.setObjectName("selectOutlets")
        self.gridLayout_4.addWidget(self.selectOutlets, 4, 0, 1, 5)
        self.outletsWidget = QtWidgets.QWidget(self.delinTab)
        self.outletsWidget.setEnabled(True)
        self.outletsWidget.setObjectName("outletsWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outletsWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.drawOutletsButton = QtWidgets.QPushButton(self.outletsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawOutletsButton.sizePolicy().hasHeightForWidth())
        self.drawOutletsButton.setSizePolicy(sizePolicy)
        self.drawOutletsButton.setMinimumSize(QtCore.QSize(0, 0))
        self.drawOutletsButton.setObjectName("drawOutletsButton")
        self.gridLayout_3.addWidget(self.drawOutletsButton, 0, 0, 1, 1)
        self.selectOutletsInteractiveButton = QtWidgets.QPushButton(self.outletsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectOutletsInteractiveButton.sizePolicy().hasHeightForWidth())
        self.selectOutletsInteractiveButton.setSizePolicy(sizePolicy)
        self.selectOutletsInteractiveButton.setObjectName("selectOutletsInteractiveButton")
        self.gridLayout_3.addWidget(self.selectOutletsInteractiveButton, 0, 1, 1, 1)
        self.selectOutletsInteractiveLabel = QtWidgets.QLabel(self.outletsWidget)
        self.selectOutletsInteractiveLabel.setMinimumSize(QtCore.QSize(111, 0))
        self.selectOutletsInteractiveLabel.setText("")
        self.selectOutletsInteractiveLabel.setObjectName("selectOutletsInteractiveLabel")
        self.gridLayout_3.addWidget(self.selectOutletsInteractiveLabel, 0, 2, 1, 1)
        self.snapThresholdLabel = QtWidgets.QLabel(self.outletsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapThresholdLabel.sizePolicy().hasHeightForWidth())
        self.snapThresholdLabel.setSizePolicy(sizePolicy)
        self.snapThresholdLabel.setMinimumSize(QtCore.QSize(0, 13))
        self.snapThresholdLabel.setObjectName("snapThresholdLabel")
        self.gridLayout_3.addWidget(self.snapThresholdLabel, 1, 0, 1, 2)
        self.snapThreshold = QtWidgets.QLineEdit(self.outletsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapThreshold.sizePolicy().hasHeightForWidth())
        self.snapThreshold.setSizePolicy(sizePolicy)
        self.snapThreshold.setMinimumSize(QtCore.QSize(0, 0))
        self.snapThreshold.setObjectName("snapThreshold")
        self.gridLayout_3.addWidget(self.snapThreshold, 2, 0, 1, 1)
        self.snapReviewButton = QtWidgets.QPushButton(self.outletsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapReviewButton.sizePolicy().hasHeightForWidth())
        self.snapReviewButton.setSizePolicy(sizePolicy)
        self.snapReviewButton.setObjectName("snapReviewButton")
        self.gridLayout_3.addWidget(self.snapReviewButton, 2, 1, 1, 1)
        self.snappedLabel = QtWidgets.QLabel(self.outletsWidget)
        self.snappedLabel.setMinimumSize(QtCore.QSize(111, 0))
        self.snappedLabel.setText("")
        self.snappedLabel.setObjectName("snappedLabel")
        self.gridLayout_3.addWidget(self.snappedLabel, 2, 2, 1, 1)
        self.gridLayout_4.addWidget(self.outletsWidget, 5, 0, 1, 5)
        self.selectBurn = QtWidgets.QLineEdit(self.delinTab)
        self.selectBurn.setEnabled(False)
        self.selectBurn.setObjectName("selectBurn")
        self.gridLayout_4.addWidget(self.selectBurn, 1, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(425, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 6, 3, 1, 1)
        self.gridBox = QtWidgets.QCheckBox(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridBox.sizePolicy().hasHeightForWidth())
        self.gridBox.setSizePolicy(sizePolicy)
        self.gridBox.setObjectName("gridBox")
        self.gridLayout_4.addWidget(self.gridBox, 6, 0, 1, 1)
        self.gridSize = QtWidgets.QSpinBox(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridSize.sizePolicy().hasHeightForWidth())
        self.gridSize.setSizePolicy(sizePolicy)
        self.gridSize.setMinimumSize(QtCore.QSize(0, 20))
        self.gridSize.setMinimum(1)
        self.gridSize.setObjectName("gridSize")
        self.gridLayout_4.addWidget(self.gridSize, 6, 1, 1, 1)
        self.gridSizeLabel = QtWidgets.QLabel(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridSizeLabel.sizePolicy().hasHeightForWidth())
        self.gridSizeLabel.setSizePolicy(sizePolicy)
        self.gridSizeLabel.setObjectName("gridSizeLabel")
        self.gridLayout_4.addWidget(self.gridSizeLabel, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 5, 1, 1)
        self.burnButton = QtWidgets.QPushButton(self.delinTab)
        self.burnButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.burnButton.sizePolicy().hasHeightForWidth())
        self.burnButton.setSizePolicy(sizePolicy)
        self.burnButton.setObjectName("burnButton")
        self.gridLayout_4.addWidget(self.burnButton, 1, 5, 1, 1)
        self.selectOutletsButton = QtWidgets.QPushButton(self.delinTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectOutletsButton.sizePolicy().hasHeightForWidth())
        self.selectOutletsButton.setSizePolicy(sizePolicy)
        self.selectOutletsButton.setObjectName("selectOutletsButton")
        self.gridLayout_4.addWidget(self.selectOutletsButton, 4, 5, 1, 1)
        self.thresholdWidget.raise_()
        self.checkBurn.raise_()
        self.delinRunButton1.raise_()
        self.useOutlets.raise_()
        self.delinRunButton2.raise_()
        self.selectOutlets.raise_()
        self.outletsWidget.raise_()
        self.selectBurn.raise_()
        self.gridBox.raise_()
        self.gridSize.raise_()
        self.gridSizeLabel.raise_()
        self.burnButton.raise_()
        self.selectOutletsButton.raise_()
        self.tabWidget.addTab(self.delinTab, "")
        self.existTab = QtWidgets.QWidget()
        self.existTab.setObjectName("existTab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.existTab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.useGrid = QtWidgets.QCheckBox(self.existTab)
        self.useGrid.setObjectName("useGrid")
        self.gridLayout_13.addWidget(self.useGrid, 0, 0, 1, 1)
        self.drainGroupBox = QtWidgets.QGroupBox(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drainGroupBox.sizePolicy().hasHeightForWidth())
        self.drainGroupBox.setSizePolicy(sizePolicy)
        self.drainGroupBox.setObjectName("drainGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.drainGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.drainGridButton = QtWidgets.QRadioButton(self.drainGroupBox)
        self.drainGridButton.setChecked(False)
        self.drainGridButton.setObjectName("drainGridButton")
        self.gridLayout_5.addWidget(self.drainGridButton, 0, 0, 1, 1)
        self.drainTableButton = QtWidgets.QRadioButton(self.drainGroupBox)
        self.drainTableButton.setObjectName("drainTableButton")
        self.gridLayout_5.addWidget(self.drainTableButton, 0, 2, 1, 1)
        self.drainStreamsButton = QtWidgets.QRadioButton(self.drainGroupBox)
        self.drainStreamsButton.setChecked(True)
        self.drainStreamsButton.setObjectName("drainStreamsButton")
        self.gridLayout_5.addWidget(self.drainStreamsButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.drainGroupBox, 0, 1, 2, 2)
        self.selectSubbasinsLabel = QtWidgets.QLabel(self.existTab)
        self.selectSubbasinsLabel.setObjectName("selectSubbasinsLabel")
        self.gridLayout_13.addWidget(self.selectSubbasinsLabel, 1, 0, 1, 1)
        self.selectSubbasins = QtWidgets.QLineEdit(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSubbasins.sizePolicy().hasHeightForWidth())
        self.selectSubbasins.setSizePolicy(sizePolicy)
        self.selectSubbasins.setObjectName("selectSubbasins")
        self.gridLayout_13.addWidget(self.selectSubbasins, 2, 0, 1, 2)
        self.selectSubbasinsButton = QtWidgets.QPushButton(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSubbasinsButton.sizePolicy().hasHeightForWidth())
        self.selectSubbasinsButton.setSizePolicy(sizePolicy)
        self.selectSubbasinsButton.setObjectName("selectSubbasinsButton")
        self.gridLayout_13.addWidget(self.selectSubbasinsButton, 2, 2, 1, 1)
        self.selectWshedLabel = QtWidgets.QLabel(self.existTab)
        self.selectWshedLabel.setObjectName("selectWshedLabel")
        self.gridLayout_13.addWidget(self.selectWshedLabel, 3, 0, 1, 1)
        self.selectWshed = QtWidgets.QLineEdit(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectWshed.sizePolicy().hasHeightForWidth())
        self.selectWshed.setSizePolicy(sizePolicy)
        self.selectWshed.setObjectName("selectWshed")
        self.gridLayout_13.addWidget(self.selectWshed, 4, 0, 1, 2)
        self.selectWshedButton = QtWidgets.QPushButton(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectWshedButton.sizePolicy().hasHeightForWidth())
        self.selectWshedButton.setSizePolicy(sizePolicy)
        self.selectWshedButton.setObjectName("selectWshedButton")
        self.gridLayout_13.addWidget(self.selectWshedButton, 4, 2, 1, 1)
        self.selectStreamsLabel = QtWidgets.QLabel(self.existTab)
        self.selectStreamsLabel.setObjectName("selectStreamsLabel")
        self.gridLayout_13.addWidget(self.selectStreamsLabel, 5, 0, 1, 1)
        self.selectStreams = QtWidgets.QLineEdit(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectStreams.sizePolicy().hasHeightForWidth())
        self.selectStreams.setSizePolicy(sizePolicy)
        self.selectStreams.setObjectName("selectStreams")
        self.gridLayout_13.addWidget(self.selectStreams, 6, 0, 1, 2)
        self.selectStreamsButton = QtWidgets.QPushButton(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectStreamsButton.sizePolicy().hasHeightForWidth())
        self.selectStreamsButton.setSizePolicy(sizePolicy)
        self.selectStreamsButton.setObjectName("selectStreamsButton")
        self.gridLayout_13.addWidget(self.selectStreamsButton, 6, 2, 1, 1)
        self.selectExistOutletsLabel = QtWidgets.QLabel(self.existTab)
        self.selectExistOutletsLabel.setObjectName("selectExistOutletsLabel")
        self.gridLayout_13.addWidget(self.selectExistOutletsLabel, 7, 0, 1, 2)
        self.selectExistOutlets = QtWidgets.QLineEdit(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectExistOutlets.sizePolicy().hasHeightForWidth())
        self.selectExistOutlets.setSizePolicy(sizePolicy)
        self.selectExistOutlets.setObjectName("selectExistOutlets")
        self.gridLayout_13.addWidget(self.selectExistOutlets, 8, 0, 1, 2)
        self.selectExistOutletsButton = QtWidgets.QPushButton(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectExistOutletsButton.sizePolicy().hasHeightForWidth())
        self.selectExistOutletsButton.setSizePolicy(sizePolicy)
        self.selectExistOutletsButton.setObjectName("selectExistOutletsButton")
        self.gridLayout_13.addWidget(self.selectExistOutletsButton, 8, 2, 1, 1)
        self.existFieldsLabel = QtWidgets.QLabel(self.existTab)
        self.existFieldsLabel.setObjectName("existFieldsLabel")
        self.gridLayout_13.addWidget(self.existFieldsLabel, 9, 0, 1, 2)
        self.widget_3 = QtWidgets.QWidget(self.existTab)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.reuseButton = QtWidgets.QRadioButton(self.widget_3)
        self.reuseButton.setChecked(True)
        self.reuseButton.setObjectName("reuseButton")
        self.gridLayout_11.addWidget(self.reuseButton, 0, 0, 1, 1)
        self.recalcButton = QtWidgets.QRadioButton(self.widget_3)
        self.recalcButton.setObjectName("recalcButton")
        self.gridLayout_11.addWidget(self.recalcButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.widget_3, 10, 0, 1, 2)
        self.existRunButton = QtWidgets.QPushButton(self.existTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.existRunButton.sizePolicy().hasHeightForWidth())
        self.existRunButton.setSizePolicy(sizePolicy)
        self.existRunButton.setObjectName("existRunButton")
        self.gridLayout_13.addWidget(self.existRunButton, 10, 2, 1, 1)
        self.tabWidget.addTab(self.existTab, "")
        self.DEMTab = QtWidgets.QWidget()
        self.DEMTab.setObjectName("DEMTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.DEMTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridWidget = QtWidgets.QWidget(self.DEMTab)
        self.gridWidget.setObjectName("gridWidget")
        self.sizeEdit = QtWidgets.QLineEdit(self.gridWidget)
        self.sizeEdit.setGeometry(QtCore.QRect(5, 80, 81, 20))
        self.sizeEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sizeEdit.setObjectName("sizeEdit")
        self.cellSize = QtWidgets.QLabel(self.gridWidget)
        self.cellSize.setGeometry(QtCore.QRect(5, 60, 91, 16))
        self.cellSize.setObjectName("cellSize")
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        self.label_3.setGeometry(QtCore.QRect(5, 120, 131, 16))
        self.label_3.setObjectName("label_3")
        self.areaEdit = QtWidgets.QLineEdit(self.gridWidget)
        self.areaEdit.setGeometry(QtCore.QRect(135, 80, 81, 20))
        self.areaEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.areaEdit.setObjectName("areaEdit")
        self.verticalCombo = QtWidgets.QComboBox(self.gridWidget)
        self.verticalCombo.setGeometry(QtCore.QRect(135, 20, 69, 22))
        self.verticalCombo.setObjectName("verticalCombo")
        self.vertiicalUnits = QtWidgets.QLabel(self.gridWidget)
        self.vertiicalUnits.setGeometry(QtCore.QRect(135, 0, 91, 16))
        self.vertiicalUnits.setObjectName("vertiicalUnits")
        self.horizontalUnits = QtWidgets.QLabel(self.gridWidget)
        self.horizontalUnits.setGeometry(QtCore.QRect(5, 0, 131, 16))
        self.horizontalUnits.setObjectName("horizontalUnits")
        self.horizontalCombo = QtWidgets.QComboBox(self.gridWidget)
        self.horizontalCombo.setGeometry(QtCore.QRect(5, 20, 69, 22))
        self.horizontalCombo.setObjectName("horizontalCombo")
        self.cellArea = QtWidgets.QLabel(self.gridWidget)
        self.cellArea.setGeometry(QtCore.QRect(135, 60, 101, 16))
        self.cellArea.setObjectName("cellArea")
        self.widget = QtWidgets.QWidget(self.gridWidget)
        self.widget.setGeometry(QtCore.QRect(0, 140, 231, 146))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 0, 46, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 41, 20))
        self.label_5.setObjectName("label_5")
        self.northEdit = QtWidgets.QLineEdit(self.widget)
        self.northEdit.setGeometry(QtCore.QRect(100, 20, 130, 20))
        self.northEdit.setObjectName("northEdit")
        self.southEdit = QtWidgets.QLineEdit(self.widget)
        self.southEdit.setGeometry(QtCore.QRect(0, 110, 130, 20))
        self.southEdit.setObjectName("southEdit")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(150, 60, 46, 13))
        self.label_6.setObjectName("label_6")
        self.westEdit = QtWidgets.QLineEdit(self.widget)
        self.westEdit.setGeometry(QtCore.QRect(0, 50, 130, 20))
        self.westEdit.setObjectName("westEdit")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 46, 13))
        self.label_7.setObjectName("label_7")
        self.eastEdit = QtWidgets.QLineEdit(self.widget)
        self.eastEdit.setGeometry(QtCore.QRect(100, 80, 130, 20))
        self.eastEdit.setObjectName("eastEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridWidget)
        self.textBrowser.setGeometry(QtCore.QRect(240, 30, 261, 260))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.gridWidget)
        self.label.setGeometry(QtCore.QRect(240, 0, 261, 21))
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.gridWidget, 0, 0, 2, 2)
        self.tabWidget.addTab(self.DEMTab, "")
        self.outputTab = QtWidgets.QWidget()
        self.outputTab.setObjectName("outputTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.outputTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.taudemOutput = QtWidgets.QTextEdit(self.outputTab)
        self.taudemOutput.setObjectName("taudemOutput")
        self.gridLayout_9.addWidget(self.taudemOutput, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.outputTab)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(451, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.taudemHelpButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taudemHelpButton.sizePolicy().hasHeightForWidth())
        self.taudemHelpButton.setSizePolicy(sizePolicy)
        self.taudemHelpButton.setObjectName("taudemHelpButton")
        self.horizontalLayout_8.addWidget(self.taudemHelpButton)
        self.gridLayout_9.addWidget(self.widget_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.outputTab, "")
        self.gridLayout_14.addWidget(self.tabWidget, 1, 0, 1, 5)
        self.numProcesses = QtWidgets.QSpinBox(DelineationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcesses.sizePolicy().hasHeightForWidth())
        self.numProcesses.setSizePolicy(sizePolicy)
        self.numProcesses.setMinimumSize(QtCore.QSize(0, 20))
        self.numProcesses.setObjectName("numProcesses")
        self.gridLayout_14.addWidget(self.numProcesses, 3, 0, 1, 1)
        self.numProcessesLabel = QtWidgets.QLabel(DelineationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcessesLabel.sizePolicy().hasHeightForWidth())
        self.numProcessesLabel.setSizePolicy(sizePolicy)
        self.numProcessesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numProcessesLabel.setWordWrap(True)
        self.numProcessesLabel.setObjectName("numProcessesLabel")
        self.gridLayout_14.addWidget(self.numProcessesLabel, 3, 1, 1, 1)
        self.showTaudem = QtWidgets.QCheckBox(DelineationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTaudem.sizePolicy().hasHeightForWidth())
        self.showTaudem.setSizePolicy(sizePolicy)
        self.showTaudem.setObjectName("showTaudem")
        self.gridLayout_14.addWidget(self.showTaudem, 3, 2, 1, 1)
        self.progressLabel = QtWidgets.QLabel(DelineationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        self.progressLabel.setText("")
        self.progressLabel.setWordWrap(True)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_14.addWidget(self.progressLabel, 3, 3, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(DelineationDialog)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.horizontalWidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.OKButton = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton.sizePolicy().hasHeightForWidth())
        self.OKButton.setSizePolicy(sizePolicy)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout_8.addWidget(self.OKButton, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_8.addWidget(self.cancelButton, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.horizontalWidget, 3, 4, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(DelineationDialog)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.landscapeTab = QtWidgets.QWidget()
        self.landscapeTab.setObjectName("landscapeTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.landscapeTab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.landscapeGroup = QtWidgets.QGroupBox(self.landscapeTab)
        self.landscapeGroup.setObjectName("landscapeGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.landscapeGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(518, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.landscapeButton = QtWidgets.QPushButton(self.landscapeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landscapeButton.sizePolicy().hasHeightForWidth())
        self.landscapeButton.setSizePolicy(sizePolicy)
        self.landscapeButton.setMinimumSize(QtCore.QSize(0, 0))
        self.landscapeButton.setObjectName("landscapeButton")
        self.gridLayout_2.addWidget(self.landscapeButton, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.landscapeGroup, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.landscapeTab, "")
        self.mergeTab = QtWidgets.QWidget()
        self.mergeTab.setObjectName("mergeTab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.mergeTab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.mergeGroup = QtWidgets.QGroupBox(self.mergeTab)
        self.mergeGroup.setMinimumSize(QtCore.QSize(0, 0))
        self.mergeGroup.setObjectName("mergeGroup")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mergeGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.selectSubButton = QtWidgets.QPushButton(self.mergeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSubButton.sizePolicy().hasHeightForWidth())
        self.selectSubButton.setSizePolicy(sizePolicy)
        self.selectSubButton.setMinimumSize(QtCore.QSize(150, 0))
        self.selectSubButton.setObjectName("selectSubButton")
        self.gridLayout_7.addWidget(self.selectSubButton, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        self.mergeButton = QtWidgets.QPushButton(self.mergeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mergeButton.sizePolicy().hasHeightForWidth())
        self.mergeButton.setSizePolicy(sizePolicy)
        self.mergeButton.setObjectName("mergeButton")
        self.gridLayout_7.addWidget(self.mergeButton, 0, 2, 1, 1)
        self.gridLayout_16.addWidget(self.mergeGroup, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.mergeTab, "")
        self.lakesTab = QtWidgets.QWidget()
        self.lakesTab.setObjectName("lakesTab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.lakesTab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lakesGroup = QtWidgets.QGroupBox(self.lakesTab)
        self.lakesGroup.setObjectName("lakesGroup")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.lakesGroup)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.selectLakesButton = QtWidgets.QPushButton(self.lakesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLakesButton.sizePolicy().hasHeightForWidth())
        self.selectLakesButton.setSizePolicy(sizePolicy)
        self.selectLakesButton.setObjectName("selectLakesButton")
        self.gridLayout_12.addWidget(self.selectLakesButton, 0, 4, 1, 1)
        self.removeLakeCells = QtWidgets.QPushButton(self.lakesGroup)
        self.removeLakeCells.setObjectName("removeLakeCells")
        self.gridLayout_12.addWidget(self.removeLakeCells, 2, 3, 1, 1)
        self.lakeIdCombo = QtWidgets.QComboBox(self.lakesGroup)
        self.lakeIdCombo.setEditable(False)
        self.lakeIdCombo.setObjectName("lakeIdCombo")
        self.gridLayout_12.addWidget(self.lakeIdCombo, 2, 1, 1, 1)
        self.selectLakes = QtWidgets.QLineEdit(self.lakesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLakes.sizePolicy().hasHeightForWidth())
        self.selectLakes.setSizePolicy(sizePolicy)
        self.selectLakes.setObjectName("selectLakes")
        self.gridLayout_12.addWidget(self.selectLakes, 0, 0, 1, 4)
        self.lakeIdLabel = QtWidgets.QLabel(self.lakesGroup)
        self.lakeIdLabel.setObjectName("lakeIdLabel")
        self.gridLayout_12.addWidget(self.lakeIdLabel, 2, 2, 1, 1)
        self.addLakeCells = QtWidgets.QPushButton(self.lakesGroup)
        self.addLakeCells.setObjectName("addLakeCells")
        self.gridLayout_12.addWidget(self.addLakeCells, 2, 4, 1, 1)
        self.lakeMessagesBox = QtWidgets.QCheckBox(self.lakesGroup)
        self.lakeMessagesBox.setObjectName("lakeMessagesBox")
        self.gridLayout_12.addWidget(self.lakeMessagesBox, 2, 0, 1, 1)
        self.gridLayout_17.addWidget(self.lakesGroup, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.lakesTab, "")
        self.gridLayout_14.addWidget(self.tabWidget_2, 2, 0, 1, 5)

        self.retranslateUi(DelineationDialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DelineationDialog)

    def retranslateUi(self, DelineationDialog):
        _translate = QtCore.QCoreApplication.translate
        DelineationDialog.setWindowTitle(_translate("DelineationDialog", "Delineate Watershed"))
        self.demGroup.setTitle(_translate("DelineationDialog", "Select DEM"))
        self.selectDemButton.setToolTip(_translate("DelineationDialog", "The digital elevation map, or DEM, is the basis for watershed delineation.  Click this button to select a DEM file."))
        self.selectDemButton.setText(_translate("DelineationDialog", ". . ."))
        self.thresholdLabelCh.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The threshold number of cells is the minimum number required to form a channel at a leaf of the channel network.</p></body></html>"))
        self.thresholdLabelCh.setText(_translate("DelineationDialog", "     Channel threshold"))
        self.numCellsCh.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The minimum number of cells required to create a channel as a leaf of the channel network</p></body></html>"))
        self.numCellsLabelCh.setToolTip(_translate("DelineationDialog", "The threshold number of cells is the minimum number required to form a stream at a leaf of the stream network."))
        self.numCellsLabelCh.setText(_translate("DelineationDialog", "Cells"))
        self.areaCh.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The minimum area required to create a channel as a leaf of the channel network</p></body></html>"))
        self.areaLabelCh.setText(_translate("DelineationDialog", "Area"))
        self.thresholdLabelSt.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The threshold number of cells is the minimum number required to form a stream (and hence a subbasin) at a leaf of the stream network.</p></body></html>"))
        self.thresholdLabelSt.setText(_translate("DelineationDialog", "       Stream threshold"))
        self.numCellsSt.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The threshold number of cells is the minimum number required to form a stream (and hence a subbasin) at a leaf of the stream network.</p></body></html>"))
        self.numCellsLabelSt.setToolTip(_translate("DelineationDialog", "The threshold number of cells is the minimum number required to form a stream at a leaf of the stream network."))
        self.numCellsLabelSt.setText(_translate("DelineationDialog", "Cells"))
        self.areaSt.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>The minimum area required to create a stream (and hence a subbasin) as a leaf of the stream network</p></body></html>"))
        self.areaLabelSt.setText(_translate("DelineationDialog", "Area"))
        self.checkBurn.setToolTip(_translate("DelineationDialog", "An existing stream network may be burnt in to make delineation more accurate, particularly in flat areas"))
        self.checkBurn.setText(_translate("DelineationDialog", "Burn in existing stream network"))
        self.delinRunButton1.setToolTip(_translate("DelineationDialog", "Create streams first if you want to place inlets/outlets interactively."))
        self.delinRunButton1.setText(_translate("DelineationDialog", "Create streams"))
        self.useOutlets.setToolTip(_translate("DelineationDialog", "The inlets outlets file defines inlets, outlets, reservoirs and point sources.  It must contain at least one outlet."))
        self.useOutlets.setText(_translate("DelineationDialog", "Use an inlets/outlets shapefile"))
        self.delinRunButton2.setToolTip(_translate("DelineationDialog", "Create the streams and the watershed and subbasin boundaries."))
        self.delinRunButton2.setText(_translate("DelineationDialog", "Create watershed"))
        self.drawOutletsButton.setToolTip(_translate("DelineationDialog", "Place inlets, outlets, reservoirs, and point sources by clicking on the stream network."))
        self.drawOutletsButton.setText(_translate("DelineationDialog", "Draw inlets/outlets"))
        self.selectOutletsInteractiveButton.setToolTip(_translate("DelineationDialog", "Interactively select which inlets, outlets, reservoirs and point sources to use. You only need to do this if you want to use only a subset of what is in the shapefile. The default is to use all the points in the shapefile."))
        self.selectOutletsInteractiveButton.setText(_translate("DelineationDialog", "Select inlets/outlets"))
        self.selectOutletsInteractiveLabel.setToolTip(_translate("DelineationDialog", "The number of points in the inlets/outlets shapefile that will be used."))
        self.snapThresholdLabel.setText(_translate("DelineationDialog", "Snap threshold (metres)"))
        self.snapThreshold.setToolTip(_translate("DelineationDialog", "The maximum distance a point may be moved to place it on the stream network (snapped).  Points which would require more than this distance will not be used."))
        self.snapReviewButton.setToolTip(_translate("DelineationDialog", "Optionally, click to load and view the snapped inlets/outlets layer. The snapped points will be used whether you load them or not."))
        self.snapReviewButton.setText(_translate("DelineationDialog", "Review snapped"))
        self.snappedLabel.setToolTip(_translate("DelineationDialog", "The number of points successfully snapped to the stream network."))
        self.gridBox.setToolTip(_translate("DelineationDialog", "This option creates a grid of squares covering your watershed (running TauDEM first to create it)  The squares replace the subbasins originally created by TauDEM."))
        self.gridBox.setText(_translate("DelineationDialog", "Make grid"))
        self.gridSize.setToolTip(_translate("DelineationDialog", "Set the size of each side of the grid squares in terms of a number of DEM cells."))
        self.gridSizeLabel.setText(_translate("DelineationDialog", "Grid size"))
        self.burnButton.setToolTip(_translate("DelineationDialog", "An existing stream network may be burnt in to make delineation more accurate, particularly in flat areas.  Click this button to select a streams file for burning in."))
        self.burnButton.setText(_translate("DelineationDialog", ". . ."))
        self.selectOutletsButton.setToolTip(_translate("DelineationDialog", "The inlets outlets file defines inlets, outlets, reservoirs and point sources.  It must contain at least one outlet.  Click this button to select an inlets/outlets shapefile."))
        self.selectOutletsButton.setText(_translate("DelineationDialog", ". . ."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delinTab), _translate("DelineationDialog", "Delineate watershed"))
        self.useGrid.setToolTip(_translate("DelineationDialog", "Use a watershed grid to define the watershed and subbasins."))
        self.useGrid.setText(_translate("DelineationDialog", "Use grid model"))
        self.drainGroupBox.setTitle(_translate("DelineationDialog", "Drainage definition"))
        self.drainGridButton.setToolTip(_translate("DelineationDialog", "Use PolygonId and DownId fields in the watershed shapefile to define the drainage pattern."))
        self.drainGridButton.setText(_translate("DelineationDialog", "Grid shapefile"))
        self.drainTableButton.setToolTip(_translate("DelineationDialog", "Use a csv file to define the drainage pattern."))
        self.drainTableButton.setText(_translate("DelineationDialog", "Drainage table"))
        self.drainStreamsButton.setToolTip(_translate("DelineationDialog", "Use a streams shapefile to define the drainage pattern."))
        self.drainStreamsButton.setText(_translate("DelineationDialog", "Streams shapefile    "))
        self.selectSubbasinsLabel.setText(_translate("DelineationDialog", "Subbasins shapefile"))
        self.selectSubbasinsButton.setToolTip(_translate("DelineationDialog", "Select a polygon shapefile showing the subbasins and watershed boundary"))
        self.selectSubbasinsButton.setText(_translate("DelineationDialog", ". . ."))
        self.selectWshedLabel.setText(_translate("DelineationDialog", "Watershed shapefile"))
        self.selectWshedButton.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>Select a polygon shapefile showing the drainage areas for all the channels in the channels shapefile.</p><p><br/></p><p>This is usually more detailed than the subbasins shapefile, but can be the same file.</p><p><br/></p></body></html>"))
        self.selectWshedButton.setText(_translate("DelineationDialog", ". . ."))
        self.selectStreamsLabel.setText(_translate("DelineationDialog", "Streams shapefile"))
        self.selectStreamsButton.setToolTip(_translate("DelineationDialog", "Select a line shapefile showing the stream network"))
        self.selectStreamsButton.setText(_translate("DelineationDialog", ". . ."))
        self.selectExistOutletsLabel.setText(_translate("DelineationDialog", "Inlets/outlets shapefile (optional)"))
        self.selectExistOutletsButton.setToolTip(_translate("DelineationDialog", "Select a point shapefile showing inlets, outlets, reservoirs and point sources.  If you do not use this option your watershed will have only outlets where the stream network exits from the watershed boundary."))
        self.selectExistOutletsButton.setText(_translate("DelineationDialog", ". . ."))
        self.existFieldsLabel.setToolTip(_translate("DelineationDialog", "Policy for calculating values like subbasin area and stream length for placing in database.  Fields in shapefiles are not actually changed by either policy."))
        self.existFieldsLabel.setText(_translate("DelineationDialog", "Existing calculated fields policy"))
        self.reuseButton.setToolTip(_translate("DelineationDialog", "Reuse existing fields like area and length from shapefiles"))
        self.reuseButton.setText(_translate("DelineationDialog", "Reuse"))
        self.recalcButton.setToolTip(_translate("DelineationDialog", "Recalculate existing fields like area and length even if found in shapefiles"))
        self.recalcButton.setText(_translate("DelineationDialog", "Recalculate and overwrite existing"))
        self.existRunButton.setToolTip(_translate("DelineationDialog", "Delineate the watershed"))
        self.existRunButton.setText(_translate("DelineationDialog", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.existTab), _translate("DelineationDialog", "Use existing watershed"))
        self.cellSize.setText(_translate("DelineationDialog", "Cell size (m)"))
        self.label_3.setText(_translate("DelineationDialog", "Extent in degrees"))
        self.vertiicalUnits.setText(_translate("DelineationDialog", "Vertical units"))
        self.horizontalUnits.setText(_translate("DelineationDialog", "Horizontal units"))
        self.cellArea.setText(_translate("DelineationDialog", "Cell area (ha)"))
        self.label_4.setText(_translate("DelineationDialog", "North"))
        self.label_5.setText(_translate("DelineationDialog", "West"))
        self.label_6.setText(_translate("DelineationDialog", "East"))
        self.label_7.setText(_translate("DelineationDialog", "South"))
        self.label.setText(_translate("DelineationDialog", "Spatial reference"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DEMTab), _translate("DelineationDialog", "DEM properties"))
        self.taudemHelpButton.setText(_translate("DelineationDialog", "TauDEM help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), _translate("DelineationDialog", "TauDEM output"))
        self.numProcesses.setToolTip(_translate("DelineationDialog", "Number of processes mpiexec should use.  0 means do not use mpiexec."))
        self.numProcessesLabel.setToolTip(_translate("DelineationDialog", "Number of processes mpiexec should use.  0 means do not use mpiexec."))
        self.numProcessesLabel.setText(_translate("DelineationDialog", "Number of processes"))
        self.showTaudem.setText(_translate("DelineationDialog", "Show Taudem\n"
"output"))
        self.OKButton.setText(_translate("DelineationDialog", "OK"))
        self.cancelButton.setText(_translate("DelineationDialog", "Cancel"))
        self.landscapeGroup.setTitle(_translate("DelineationDialog", "Create landscape"))
        self.landscapeButton.setToolTip(_translate("DelineationDialog", "Create landscape units, which will subdivide each subbasin into floodplain and upslope areas."))
        self.landscapeButton.setText(_translate("DelineationDialog", "Create"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.landscapeTab), _translate("DelineationDialog", "Create landscape"))
        self.mergeGroup.setTitle(_translate("DelineationDialog", "Merge subbasins"))
        self.selectSubButton.setToolTip(_translate("DelineationDialog", "Select a subbasin for merging with its downstream subbasin."))
        self.selectSubButton.setText(_translate("DelineationDialog", "Select subbasins"))
        self.mergeButton.setToolTip(_translate("DelineationDialog", "Perform the merge."))
        self.mergeButton.setText(_translate("DelineationDialog", "Merge"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.mergeTab), _translate("DelineationDialog", "Merge subbasins"))
        self.lakesGroup.setTitle(_translate("DelineationDialog", "Add lakes shapefile"))
        self.selectLakesButton.setToolTip(_translate("DelineationDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">A shapefile showing the outline of lakes as polygons may be added.  Click this button to select the shapefile.</span></p></body></html>"))
        self.selectLakesButton.setText(_translate("DelineationDialog", ". . ."))
        self.removeLakeCells.setText(_translate("DelineationDialog", "Remove lake cells"))
        self.lakeIdLabel.setText(_translate("DelineationDialog", "Lake number"))
        self.addLakeCells.setText(_translate("DelineationDialog", "Add lake cells"))
        self.lakeMessagesBox.setToolTip(_translate("DelineationDialog", "<html><head/><body><p>Lake shapefiles with many lakes can generate a large number of warning and information messages. Check this box if you prefer to read these messages in the QSWAT+ log.</p></body></html>"))
        self.lakeMessagesBox.setText(_translate("DelineationDialog", "Don\'t display lake messages"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.lakesTab), _translate("DelineationDialog", "Add Lakes"))

from . import resources_rc
