# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_hrus2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_7 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.HRUsTab = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HRUsTab.sizePolicy().hasHeightForWidth())
        self.HRUsTab.setSizePolicy(sizePolicy)
        self.HRUsTab.setObjectName("HRUsTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectLanduseLabel = QtWidgets.QLabel(self.tab)
        self.selectLanduseLabel.setObjectName("selectLanduseLabel")
        self.gridLayout_2.addWidget(self.selectLanduseLabel, 0, 0, 1, 1)
        self.selectLanduseButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLanduseButton.sizePolicy().hasHeightForWidth())
        self.selectLanduseButton.setSizePolicy(sizePolicy)
        self.selectLanduseButton.setAutoFillBackground(False)
        self.selectLanduseButton.setAutoDefault(False)
        self.selectLanduseButton.setFlat(False)
        self.selectLanduseButton.setProperty("browseButton", True)
        self.selectLanduseButton.setObjectName("selectLanduseButton")
        self.gridLayout_2.addWidget(self.selectLanduseButton, 1, 3, 1, 1)
        self.selectSoilLabel = QtWidgets.QLabel(self.tab)
        self.selectSoilLabel.setObjectName("selectSoilLabel")
        self.gridLayout_2.addWidget(self.selectSoilLabel, 2, 0, 1, 1)
        self.selectSoilButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSoilButton.sizePolicy().hasHeightForWidth())
        self.selectSoilButton.setSizePolicy(sizePolicy)
        self.selectSoilButton.setAutoDefault(False)
        self.selectSoilButton.setObjectName("selectSoilButton")
        self.gridLayout_2.addWidget(self.selectSoilButton, 3, 3, 1, 1)
        self.dbLabel = QtWidgets.QLabel(self.tab)
        self.dbLabel.setObjectName("dbLabel")
        self.gridLayout_2.addWidget(self.dbLabel, 4, 0, 1, 1)
        self.selectPlantSoilDatabaseButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPlantSoilDatabaseButton.sizePolicy().hasHeightForWidth())
        self.selectPlantSoilDatabaseButton.setSizePolicy(sizePolicy)
        self.selectPlantSoilDatabaseButton.setAutoDefault(False)
        self.selectPlantSoilDatabaseButton.setObjectName("selectPlantSoilDatabaseButton")
        self.gridLayout_2.addWidget(self.selectPlantSoilDatabaseButton, 5, 3, 1, 1)
        self.soilGroup = QtWidgets.QGroupBox(self.tab)
        self.soilGroup.setMinimumSize(QtCore.QSize(0, 0))
        self.soilGroup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.soilGroup.setObjectName("soilGroup")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.soilGroup)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.usersoilButton = QtWidgets.QRadioButton(self.soilGroup)
        self.usersoilButton.setChecked(True)
        self.usersoilButton.setObjectName("usersoilButton")
        self.gridLayout_15.addWidget(self.usersoilButton, 0, 0, 1, 1)
        self.STATSGOButton = QtWidgets.QRadioButton(self.soilGroup)
        self.STATSGOButton.setObjectName("STATSGOButton")
        self.gridLayout_15.addWidget(self.STATSGOButton, 1, 0, 1, 1)
        self.SSURGOButton = QtWidgets.QRadioButton(self.soilGroup)
        self.SSURGOButton.setObjectName("SSURGOButton")
        self.gridLayout_15.addWidget(self.SSURGOButton, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.soilGroup, 6, 0, 1, 1)
        self.tableGroup = QtWidgets.QGroupBox(self.tab)
        self.tableGroup.setObjectName("tableGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tableGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.landuseTableLabel = QtWidgets.QLabel(self.tableGroup)
        self.landuseTableLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.landuseTableLabel.setObjectName("landuseTableLabel")
        self.gridLayout_3.addWidget(self.landuseTableLabel, 0, 0, 1, 1)
        self.selectLanduseTable = QtWidgets.QComboBox(self.tableGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLanduseTable.sizePolicy().hasHeightForWidth())
        self.selectLanduseTable.setSizePolicy(sizePolicy)
        self.selectLanduseTable.setObjectName("selectLanduseTable")
        self.gridLayout_3.addWidget(self.selectLanduseTable, 0, 1, 1, 1)
        self.soilTableLabel = QtWidgets.QLabel(self.tableGroup)
        self.soilTableLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soilTableLabel.setObjectName("soilTableLabel")
        self.gridLayout_3.addWidget(self.soilTableLabel, 1, 0, 1, 1)
        self.selectSoilTable = QtWidgets.QComboBox(self.tableGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSoilTable.sizePolicy().hasHeightForWidth())
        self.selectSoilTable.setSizePolicy(sizePolicy)
        self.selectSoilTable.setObjectName("selectSoilTable")
        self.gridLayout_3.addWidget(self.selectSoilTable, 1, 1, 1, 1)
        self.selectUsersoilTableLabel = QtWidgets.QLabel(self.tableGroup)
        self.selectUsersoilTableLabel.setScaledContents(False)
        self.selectUsersoilTableLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selectUsersoilTableLabel.setObjectName("selectUsersoilTableLabel")
        self.gridLayout_3.addWidget(self.selectUsersoilTableLabel, 2, 0, 1, 1)
        self.selectUsersoilTable = QtWidgets.QComboBox(self.tableGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectUsersoilTable.sizePolicy().hasHeightForWidth())
        self.selectUsersoilTable.setSizePolicy(sizePolicy)
        self.selectUsersoilTable.setObjectName("selectUsersoilTable")
        self.gridLayout_3.addWidget(self.selectUsersoilTable, 2, 1, 1, 1)
        self.selectPlantTableLabel = QtWidgets.QLabel(self.tableGroup)
        self.selectPlantTableLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selectPlantTableLabel.setObjectName("selectPlantTableLabel")
        self.gridLayout_3.addWidget(self.selectPlantTableLabel, 3, 0, 1, 1)
        self.selectPlantTable = QtWidgets.QComboBox(self.tableGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPlantTable.sizePolicy().hasHeightForWidth())
        self.selectPlantTable.setSizePolicy(sizePolicy)
        self.selectPlantTable.setObjectName("selectPlantTable")
        self.gridLayout_3.addWidget(self.selectPlantTable, 3, 1, 1, 1)
        self.selectUrbanTableLabel = QtWidgets.QLabel(self.tableGroup)
        self.selectUrbanTableLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selectUrbanTableLabel.setObjectName("selectUrbanTableLabel")
        self.gridLayout_3.addWidget(self.selectUrbanTableLabel, 4, 0, 1, 1)
        self.selectUrbanTable = QtWidgets.QComboBox(self.tableGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectUrbanTable.sizePolicy().hasHeightForWidth())
        self.selectUrbanTable.setSizePolicy(sizePolicy)
        self.selectUrbanTable.setObjectName("selectUrbanTable")
        self.gridLayout_3.addWidget(self.selectUrbanTable, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.tableGroup, 6, 1, 2, 2)
        self.slopeGroup = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slopeGroup.sizePolicy().hasHeightForWidth())
        self.slopeGroup.setSizePolicy(sizePolicy)
        self.slopeGroup.setMaximumSize(QtCore.QSize(150, 16777215))
        self.slopeGroup.setObjectName("slopeGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.slopeGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.clearButton = QtWidgets.QPushButton(self.slopeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setAutoDefault(False)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_4.addWidget(self.clearButton, 1, 1, 1, 1)
        self.slopeBand = QtWidgets.QLineEdit(self.slopeGroup)
        self.slopeBand.setObjectName("slopeBand")
        self.gridLayout_4.addWidget(self.slopeBand, 0, 0, 1, 1)
        self.slopeBandsLabel = QtWidgets.QLabel(self.slopeGroup)
        self.slopeBandsLabel.setObjectName("slopeBandsLabel")
        self.gridLayout_4.addWidget(self.slopeBandsLabel, 2, 0, 1, 2)
        self.slopeBrowser = QtWidgets.QLineEdit(self.slopeGroup)
        self.slopeBrowser.setReadOnly(True)
        self.slopeBrowser.setObjectName("slopeBrowser")
        self.gridLayout_4.addWidget(self.slopeBrowser, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.insertButton = QtWidgets.QPushButton(self.slopeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertButton.sizePolicy().hasHeightForWidth())
        self.insertButton.setSizePolicy(sizePolicy)
        self.insertButton.setAutoDefault(False)
        self.insertButton.setObjectName("insertButton")
        self.gridLayout_4.addWidget(self.insertButton, 0, 1, 1, 1)
        self.clearButton.raise_()
        self.slopeBand.raise_()
        self.slopeBandsLabel.raise_()
        self.slopeBrowser.raise_()
        self.insertButton.raise_()
        self.gridLayout_2.addWidget(self.slopeGroup, 7, 0, 3, 1)
        self.floodplainCombo = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floodplainCombo.sizePolicy().hasHeightForWidth())
        self.floodplainCombo.setSizePolicy(sizePolicy)
        self.floodplainCombo.setToolTip("")
        self.floodplainCombo.setMaxVisibleItems(20)
        self.floodplainCombo.setObjectName("floodplainCombo")
        self.gridLayout_2.addWidget(self.floodplainCombo, 8, 1, 1, 1)
        self.shortChannelGroup = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortChannelGroup.sizePolicy().hasHeightForWidth())
        self.shortChannelGroup.setSizePolicy(sizePolicy)
        self.shortChannelGroup.setObjectName("shortChannelGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.shortChannelGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.channelMergeSlider = QtWidgets.QSlider(self.shortChannelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelMergeSlider.sizePolicy().hasHeightForWidth())
        self.channelMergeSlider.setSizePolicy(sizePolicy)
        self.channelMergeSlider.setMaximum(100)
        self.channelMergeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.channelMergeSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.channelMergeSlider.setObjectName("channelMergeSlider")
        self.gridLayout_5.addWidget(self.channelMergeSlider, 1, 0, 1, 1)
        self.channelMergeVal = QtWidgets.QLineEdit(self.shortChannelGroup)
        self.channelMergeVal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.channelMergeVal.setObjectName("channelMergeVal")
        self.gridLayout_5.addWidget(self.channelMergeVal, 1, 1, 1, 1)
        self.channelAreaButton = QtWidgets.QRadioButton(self.shortChannelGroup)
        self.channelAreaButton.setObjectName("channelAreaButton")
        self.gridLayout_5.addWidget(self.channelAreaButton, 0, 1, 1, 1)
        self.channelPercentButton = QtWidgets.QRadioButton(self.shortChannelGroup)
        self.channelPercentButton.setChecked(True)
        self.channelPercentButton.setObjectName("channelPercentButton")
        self.gridLayout_5.addWidget(self.channelPercentButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.shortChannelGroup, 9, 1, 2, 2)
        self.reservoirBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservoirBox.sizePolicy().hasHeightForWidth())
        self.reservoirBox.setSizePolicy(sizePolicy)
        self.reservoirBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reservoirBox.setObjectName("reservoirBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.reservoirBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.reservoirThreshold = QtWidgets.QSpinBox(self.reservoirBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservoirThreshold.sizePolicy().hasHeightForWidth())
        self.reservoirThreshold.setSizePolicy(sizePolicy)
        self.reservoirThreshold.setMaximumSize(QtCore.QSize(100, 16777215))
        self.reservoirThreshold.setToolTip("")
        self.reservoirThreshold.setMaximum(101)
        self.reservoirThreshold.setProperty("value", 101)
        self.reservoirThreshold.setObjectName("reservoirThreshold")
        self.gridLayout_6.addWidget(self.reservoirThreshold, 0, 0, 1, 1)
        self.reservoirPercent = QtWidgets.QLabel(self.reservoirBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reservoirPercent.sizePolicy().hasHeightForWidth())
        self.reservoirPercent.setSizePolicy(sizePolicy)
        self.reservoirPercent.setWordWrap(True)
        self.reservoirPercent.setObjectName("reservoirPercent")
        self.gridLayout_6.addWidget(self.reservoirPercent, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.reservoirBox, 10, 0, 2, 1)
        self.readChoiceGroup = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readChoiceGroup.sizePolicy().hasHeightForWidth())
        self.readChoiceGroup.setSizePolicy(sizePolicy)
        self.readChoiceGroup.setObjectName("readChoiceGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.readChoiceGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.readFromPrevious = QtWidgets.QRadioButton(self.readChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readFromPrevious.sizePolicy().hasHeightForWidth())
        self.readFromPrevious.setSizePolicy(sizePolicy)
        self.readFromPrevious.setObjectName("readFromPrevious")
        self.gridLayout.addWidget(self.readFromPrevious, 2, 0, 1, 1)
        self.remerge = QtWidgets.QRadioButton(self.readChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remerge.sizePolicy().hasHeightForWidth())
        self.remerge.setSizePolicy(sizePolicy)
        self.remerge.setObjectName("remerge")
        self.gridLayout.addWidget(self.remerge, 3, 0, 1, 1)
        self.readFromMaps = QtWidgets.QRadioButton(self.readChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readFromMaps.sizePolicy().hasHeightForWidth())
        self.readFromMaps.setSizePolicy(sizePolicy)
        self.readFromMaps.setChecked(True)
        self.readFromMaps.setObjectName("readFromMaps")
        self.gridLayout.addWidget(self.readFromMaps, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.readChoiceGroup, 11, 1, 4, 1)
        self.generateFullHRUs = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateFullHRUs.sizePolicy().hasHeightForWidth())
        self.generateFullHRUs.setSizePolicy(sizePolicy)
        self.generateFullHRUs.setObjectName("generateFullHRUs")
        self.gridLayout_2.addWidget(self.generateFullHRUs, 11, 2, 1, 2)
        self.optionGroup = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionGroup.sizePolicy().hasHeightForWidth())
        self.optionGroup.setSizePolicy(sizePolicy)
        self.optionGroup.setMaximumSize(QtCore.QSize(180, 16777215))
        self.optionGroup.setObjectName("optionGroup")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.optionGroup)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.elevBandsButton = QtWidgets.QPushButton(self.optionGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elevBandsButton.sizePolicy().hasHeightForWidth())
        self.elevBandsButton.setSizePolicy(sizePolicy)
        self.elevBandsButton.setAutoDefault(False)
        self.elevBandsButton.setObjectName("elevBandsButton")
        self.gridLayout_14.addWidget(self.elevBandsButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.optionGroup, 12, 0, 3, 1)
        self.subbasinsLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subbasinsLabel.sizePolicy().hasHeightForWidth())
        self.subbasinsLabel.setSizePolicy(sizePolicy)
        self.subbasinsLabel.setObjectName("subbasinsLabel")
        self.gridLayout_2.addWidget(self.subbasinsLabel, 12, 3, 1, 1)
        self.channelsLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelsLabel.sizePolicy().hasHeightForWidth())
        self.channelsLabel.setSizePolicy(sizePolicy)
        self.channelsLabel.setObjectName("channelsLabel")
        self.gridLayout_2.addWidget(self.channelsLabel, 13, 3, 1, 1)
        self.fullHRUsLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullHRUsLabel.sizePolicy().hasHeightForWidth())
        self.fullHRUsLabel.setSizePolicy(sizePolicy)
        self.fullHRUsLabel.setObjectName("fullHRUsLabel")
        self.gridLayout_2.addWidget(self.fullHRUsLabel, 14, 3, 1, 1)
        self.progressLabel1 = QtWidgets.QLabel(self.tab)
        self.progressLabel1.setMinimumSize(QtCore.QSize(100, 0))
        self.progressLabel1.setObjectName("progressLabel1")
        self.gridLayout_2.addWidget(self.progressLabel1, 15, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 15, 1, 1, 1)
        self.readButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readButton.sizePolicy().hasHeightForWidth())
        self.readButton.setSizePolicy(sizePolicy)
        self.readButton.setAutoDefault(False)
        self.readButton.setObjectName("readButton")
        self.gridLayout_2.addWidget(self.readButton, 15, 3, 1, 1)
        self.selectLanduse = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLanduse.sizePolicy().hasHeightForWidth())
        self.selectLanduse.setSizePolicy(sizePolicy)
        self.selectLanduse.setObjectName("selectLanduse")
        self.gridLayout_2.addWidget(self.selectLanduse, 1, 0, 1, 2)
        self.selectSoil = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSoil.sizePolicy().hasHeightForWidth())
        self.selectSoil.setSizePolicy(sizePolicy)
        self.selectSoil.setObjectName("selectSoil")
        self.gridLayout_2.addWidget(self.selectSoil, 3, 0, 1, 2)
        self.plantSoilDatabase = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plantSoilDatabase.sizePolicy().hasHeightForWidth())
        self.plantSoilDatabase.setSizePolicy(sizePolicy)
        self.plantSoilDatabase.setObjectName("plantSoilDatabase")
        self.gridLayout_2.addWidget(self.plantSoilDatabase, 5, 0, 1, 2)
        self.HRUsTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.optionGroup_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionGroup_2.sizePolicy().hasHeightForWidth())
        self.optionGroup_2.setSizePolicy(sizePolicy)
        self.optionGroup_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.optionGroup_2.setObjectName("optionGroup_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.optionGroup_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.exemptButton = QtWidgets.QPushButton(self.optionGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exemptButton.sizePolicy().hasHeightForWidth())
        self.exemptButton.setSizePolicy(sizePolicy)
        self.exemptButton.setAutoDefault(False)
        self.exemptButton.setObjectName("exemptButton")
        self.gridLayout_16.addWidget(self.exemptButton, 1, 0, 1, 1)
        self.splitButton = QtWidgets.QPushButton(self.optionGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitButton.sizePolicy().hasHeightForWidth())
        self.splitButton.setSizePolicy(sizePolicy)
        self.splitButton.setAutoDefault(False)
        self.splitButton.setObjectName("splitButton")
        self.gridLayout_16.addWidget(self.splitButton, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.optionGroup_2, 0, 0, 1, 2)
        self.hruChoiceGroup = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hruChoiceGroup.sizePolicy().hasHeightForWidth())
        self.hruChoiceGroup.setSizePolicy(sizePolicy)
        self.hruChoiceGroup.setObjectName("hruChoiceGroup")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.hruChoiceGroup)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.filterAreaButton = QtWidgets.QRadioButton(self.hruChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterAreaButton.sizePolicy().hasHeightForWidth())
        self.filterAreaButton.setSizePolicy(sizePolicy)
        self.filterAreaButton.setObjectName("filterAreaButton")
        self.gridLayout_9.addWidget(self.filterAreaButton, 4, 0, 1, 1)
        self.dominantHRUButton = QtWidgets.QRadioButton(self.hruChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dominantHRUButton.sizePolicy().hasHeightForWidth())
        self.dominantHRUButton.setSizePolicy(sizePolicy)
        self.dominantHRUButton.setChecked(False)
        self.dominantHRUButton.setObjectName("dominantHRUButton")
        self.gridLayout_9.addWidget(self.dominantHRUButton, 2, 0, 1, 1)
        self.targetButton = QtWidgets.QRadioButton(self.hruChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetButton.sizePolicy().hasHeightForWidth())
        self.targetButton.setSizePolicy(sizePolicy)
        self.targetButton.setObjectName("targetButton")
        self.gridLayout_9.addWidget(self.targetButton, 5, 0, 1, 1)
        self.filterLanduseButton = QtWidgets.QRadioButton(self.hruChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLanduseButton.sizePolicy().hasHeightForWidth())
        self.filterLanduseButton.setSizePolicy(sizePolicy)
        self.filterLanduseButton.setChecked(True)
        self.filterLanduseButton.setObjectName("filterLanduseButton")
        self.gridLayout_9.addWidget(self.filterLanduseButton, 3, 0, 1, 1)
        self.dominantLanduseButton = QtWidgets.QRadioButton(self.hruChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dominantLanduseButton.sizePolicy().hasHeightForWidth())
        self.dominantLanduseButton.setSizePolicy(sizePolicy)
        self.dominantLanduseButton.setObjectName("dominantLanduseButton")
        self.gridLayout_9.addWidget(self.dominantLanduseButton, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.hruChoiceGroup, 0, 2, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.landuseSoilSlopeGroup = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landuseSoilSlopeGroup.sizePolicy().hasHeightForWidth())
        self.landuseSoilSlopeGroup.setSizePolicy(sizePolicy)
        self.landuseSoilSlopeGroup.setObjectName("landuseSoilSlopeGroup")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.landuseSoilSlopeGroup)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.landuseSlider = QtWidgets.QSlider(self.landuseSoilSlopeGroup)
        self.landuseSlider.setAcceptDrops(False)
        self.landuseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.landuseSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.landuseSlider.setObjectName("landuseSlider")
        self.gridLayout_12.addWidget(self.landuseSlider, 1, 0, 1, 3)
        self.landuseButton = QtWidgets.QPushButton(self.landuseSoilSlopeGroup)
        self.landuseButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.landuseButton.setAutoDefault(False)
        self.landuseButton.setObjectName("landuseButton")
        self.gridLayout_12.addWidget(self.landuseButton, 1, 3, 1, 1)
        self.landuseMin = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.landuseMin.setObjectName("landuseMin")
        self.gridLayout_12.addWidget(self.landuseMin, 0, 0, 1, 1)
        self.landuseLabel = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.landuseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.landuseLabel.setObjectName("landuseLabel")
        self.gridLayout_12.addWidget(self.landuseLabel, 0, 1, 1, 1)
        self.landuseMax = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.landuseMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.landuseMax.setObjectName("landuseMax")
        self.gridLayout_12.addWidget(self.landuseMax, 0, 2, 1, 1)
        self.landuseVal = QtWidgets.QLineEdit(self.landuseSoilSlopeGroup)
        self.landuseVal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.landuseVal.setObjectName("landuseVal")
        self.gridLayout_12.addWidget(self.landuseVal, 0, 3, 1, 1)
        self.soilMin = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.soilMin.setObjectName("soilMin")
        self.gridLayout_12.addWidget(self.soilMin, 2, 0, 1, 1)
        self.soilLabel = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.soilLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.soilLabel.setObjectName("soilLabel")
        self.gridLayout_12.addWidget(self.soilLabel, 2, 1, 1, 1)
        self.soilMax = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.soilMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soilMax.setObjectName("soilMax")
        self.gridLayout_12.addWidget(self.soilMax, 2, 2, 1, 1)
        self.soilVal = QtWidgets.QLineEdit(self.landuseSoilSlopeGroup)
        self.soilVal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.soilVal.setObjectName("soilVal")
        self.gridLayout_12.addWidget(self.soilVal, 2, 3, 1, 1)
        self.slopeSlider = QtWidgets.QSlider(self.landuseSoilSlopeGroup)
        self.slopeSlider.setAcceptDrops(False)
        self.slopeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.slopeSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slopeSlider.setObjectName("slopeSlider")
        self.gridLayout_12.addWidget(self.slopeSlider, 5, 0, 1, 3)
        self.slopeLabel = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.slopeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.slopeLabel.setObjectName("slopeLabel")
        self.gridLayout_12.addWidget(self.slopeLabel, 4, 1, 1, 1)
        self.slopeMax = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.slopeMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slopeMax.setObjectName("slopeMax")
        self.gridLayout_12.addWidget(self.slopeMax, 4, 2, 1, 1)
        self.slopeVal = QtWidgets.QLineEdit(self.landuseSoilSlopeGroup)
        self.slopeVal.setMaximumSize(QtCore.QSize(40, 16777215))
        self.slopeVal.setObjectName("slopeVal")
        self.gridLayout_12.addWidget(self.slopeVal, 4, 3, 1, 1)
        self.soilSlider = QtWidgets.QSlider(self.landuseSoilSlopeGroup)
        self.soilSlider.setAcceptDrops(False)
        self.soilSlider.setOrientation(QtCore.Qt.Horizontal)
        self.soilSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.soilSlider.setObjectName("soilSlider")
        self.gridLayout_12.addWidget(self.soilSlider, 3, 0, 1, 3)
        self.soilButton = QtWidgets.QPushButton(self.landuseSoilSlopeGroup)
        self.soilButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.soilButton.setAutoDefault(False)
        self.soilButton.setObjectName("soilButton")
        self.gridLayout_12.addWidget(self.soilButton, 3, 3, 1, 1)
        self.slopeMin = QtWidgets.QLabel(self.landuseSoilSlopeGroup)
        self.slopeMin.setObjectName("slopeMin")
        self.gridLayout_12.addWidget(self.slopeMin, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.landuseSoilSlopeGroup, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.gridLayout_100 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_100.setObjectName("gridLayout_100")
        self.areaGroup = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaGroup.sizePolicy().hasHeightForWidth())
        self.areaGroup.setSizePolicy(sizePolicy)
        self.areaGroup.setMinimumSize(QtCore.QSize(0, 100))
        self.areaGroup.setObjectName("areaGroup")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.areaGroup)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.areaMin = QtWidgets.QLabel(self.areaGroup)
        self.areaMin.setObjectName("areaMin")
        self.gridLayout_13.addWidget(self.areaMin, 0, 0, 1, 1)
        self.areaLabel = QtWidgets.QLabel(self.areaGroup)
        self.areaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.areaLabel.setObjectName("areaLabel")
        self.gridLayout_13.addWidget(self.areaLabel, 0, 1, 1, 1)
        self.areaMax = QtWidgets.QLabel(self.areaGroup)
        self.areaMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.areaMax.setObjectName("areaMax")
        self.gridLayout_13.addWidget(self.areaMax, 0, 2, 1, 1)
        self.areaSlider = QtWidgets.QSlider(self.areaGroup)
        self.areaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.areaSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.areaSlider.setObjectName("areaSlider")
        self.gridLayout_13.addWidget(self.areaSlider, 1, 0, 1, 3)
        self.areaVal = QtWidgets.QLineEdit(self.areaGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaVal.sizePolicy().hasHeightForWidth())
        self.areaVal.setSizePolicy(sizePolicy)
        self.areaVal.setMinimumSize(QtCore.QSize(50, 0))
        self.areaVal.setMaximumSize(QtCore.QSize(50, 16777215))
        self.areaVal.setObjectName("areaVal")
        self.gridLayout_13.addWidget(self.areaVal, 1, 3, 1, 1)
        self.gridLayout_100.addWidget(self.areaGroup, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.page_3.setObjectName("page_3")
        self.gridLayout_101 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_101.setObjectName("gridLayout_101")
        self.targetGroup = QtWidgets.QGroupBox(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetGroup.sizePolicy().hasHeightForWidth())
        self.targetGroup.setSizePolicy(sizePolicy)
        self.targetGroup.setMinimumSize(QtCore.QSize(0, 100))
        self.targetGroup.setObjectName("targetGroup")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.targetGroup)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.targetMin = QtWidgets.QLabel(self.targetGroup)
        self.targetMin.setWordWrap(True)
        self.targetMin.setObjectName("targetMin")
        self.gridLayout_17.addWidget(self.targetMin, 0, 0, 1, 1)
        self.targetLabel = QtWidgets.QLabel(self.targetGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetLabel.sizePolicy().hasHeightForWidth())
        self.targetLabel.setSizePolicy(sizePolicy)
        self.targetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.gridLayout_17.addWidget(self.targetLabel, 0, 1, 1, 1)
        self.targetMax = QtWidgets.QLabel(self.targetGroup)
        self.targetMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetMax.setObjectName("targetMax")
        self.gridLayout_17.addWidget(self.targetMax, 0, 2, 1, 1)
        self.targetSlider = QtWidgets.QSlider(self.targetGroup)
        self.targetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.targetSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.targetSlider.setObjectName("targetSlider")
        self.gridLayout_17.addWidget(self.targetSlider, 1, 0, 1, 2)
        self.targetVal = QtWidgets.QLineEdit(self.targetGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetVal.sizePolicy().hasHeightForWidth())
        self.targetVal.setSizePolicy(sizePolicy)
        self.targetVal.setMinimumSize(QtCore.QSize(50, 0))
        self.targetVal.setMaximumSize(QtCore.QSize(50, 16777215))
        self.targetVal.setObjectName("targetVal")
        self.gridLayout_17.addWidget(self.targetVal, 1, 2, 1, 1)
        self.gridLayout_101.addWidget(self.targetGroup, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_18.addWidget(self.stackedWidget, 0, 3, 3, 2)
        spacerItem1 = QtWidgets.QSpacerItem(106, 371, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem1, 1, 0, 3, 2)
        self.areaPercentChoiceGroup = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaPercentChoiceGroup.sizePolicy().hasHeightForWidth())
        self.areaPercentChoiceGroup.setSizePolicy(sizePolicy)
        self.areaPercentChoiceGroup.setObjectName("areaPercentChoiceGroup")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.areaPercentChoiceGroup)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.percentButton = QtWidgets.QRadioButton(self.areaPercentChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentButton.sizePolicy().hasHeightForWidth())
        self.percentButton.setSizePolicy(sizePolicy)
        self.percentButton.setChecked(True)
        self.percentButton.setObjectName("percentButton")
        self.gridLayout_11.addWidget(self.percentButton, 0, 0, 1, 1)
        self.areaButton = QtWidgets.QRadioButton(self.areaPercentChoiceGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaButton.sizePolicy().hasHeightForWidth())
        self.areaButton.setSizePolicy(sizePolicy)
        self.areaButton.setObjectName("areaButton")
        self.gridLayout_11.addWidget(self.areaButton, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.areaPercentChoiceGroup, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(188, 234, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem2, 3, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem3, 3, 3, 1, 1)
        self.progressLabel2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel2.sizePolicy().hasHeightForWidth())
        self.progressLabel2.setSizePolicy(sizePolicy)
        self.progressLabel2.setObjectName("progressLabel2")
        self.gridLayout_18.addWidget(self.progressLabel2, 4, 0, 1, 4)
        self.createButton = QtWidgets.QPushButton(self.tab_2)
        self.createButton.setAutoDefault(False)
        self.createButton.setObjectName("createButton")
        self.gridLayout_18.addWidget(self.createButton, 4, 4, 1, 1)
        self.HRUsTab.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.HRUsTab, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(408, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_8.addWidget(self.cancelButton, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.HRUsTab.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create HRUs"))
        self.selectLanduseLabel.setText(_translate("Dialog", "Select landuse map"))
        self.selectLanduseButton.setToolTip(_translate("Dialog", "Select landuse raster"))
        self.selectLanduseButton.setText(_translate("Dialog", ". . ."))
        self.selectSoilLabel.setText(_translate("Dialog", "Select soil map"))
        self.selectSoilButton.setToolTip(_translate("Dialog", "Select soil raster"))
        self.selectSoilButton.setText(_translate("Dialog", ". . ."))
        self.dbLabel.setText(_translate("Dialog", "Select landuse and soil database"))
        self.selectPlantSoilDatabaseButton.setToolTip(_translate("Dialog", "Select database with tables defining landuse and soil attributes"))
        self.selectPlantSoilDatabaseButton.setText(_translate("Dialog", ". . ."))
        self.soilGroup.setTitle(_translate("Dialog", "Soil data"))
        self.usersoilButton.setText(_translate("Dialog", "usersoil"))
        self.STATSGOButton.setText(_translate("Dialog", "STATSGO"))
        self.SSURGOButton.setText(_translate("Dialog", "SSURGO/STATSGO2"))
        self.tableGroup.setTitle(_translate("Dialog", "Tables"))
        self.landuseTableLabel.setText(_translate("Dialog", "Landuse lookup"))
        self.selectLanduseTable.setToolTip(_translate("Dialog", "<html><head/><body><p>Select table in project database mapping landuse grid values to  landuse codes defined in either a plant or urban landuse table in the landuse and soil database</p></body></html>"))
        self.soilTableLabel.setText(_translate("Dialog", "Soil lookup"))
        self.selectSoilTable.setToolTip(_translate("Dialog", "<html><head/><body><p>Select table in project database mapping soil raster values to soil names in a usersoil table in the landuse and soil database</p></body></html>"))
        self.selectUsersoilTableLabel.setText(_translate("Dialog", "Usersoil "))
        self.selectUsersoilTable.setToolTip(_translate("Dialog", "<html><head/><body><p>Select table in landuse and soil database providing soil attributes.</p></body></html>"))
        self.selectPlantTableLabel.setText(_translate("Dialog", "Plant  "))
        self.selectPlantTable.setToolTip(_translate("Dialog", "<html><head/><body><p>Select table in landuse and soil database providing plantl attributes.</p></body></html>"))
        self.selectUrbanTableLabel.setText(_translate("Dialog", "Urban"))
        self.selectUrbanTable.setToolTip(_translate("Dialog", "<html><head/><body><p>Select table in landuse and soil database providing urban landuse attributes.</p></body></html>"))
        self.slopeGroup.setTitle(_translate("Dialog", "Set slope bands (%)"))
        self.clearButton.setToolTip(_translate("Dialog", "Cancel all slope bands"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.slopeBand.setToolTip(_translate("Dialog", "Enter a slope percent value to be a new boundary between slope bands."))
        self.slopeBandsLabel.setText(_translate("Dialog", "Slope bands"))
        self.insertButton.setToolTip(_translate("Dialog", "Insert a new division between slope bands"))
        self.insertButton.setText(_translate("Dialog", "Insert"))
        self.shortChannelGroup.setToolTip(_translate("Dialog", "<html><head/><body><p>Short channels can occur when stream junctions happen to be close together. There is an option to merge them, and hence their landscape units, by selecting a threshold of either a percentage of the subbasin area or an area in hectares. Channels with a drainage area less than the threshold will, where possible, be merged with a downstream channel. Channels are not merged if they have a user-defined reservoir, or if the downstream channel is in a different subbasin. Setting the threshold to zero prevents any merging.</p></body></html>"))
        self.shortChannelGroup.setTitle(_translate("Dialog", "Short channel merge"))
        self.channelMergeVal.setText(_translate("Dialog", "0"))
        self.channelAreaButton.setText(_translate("Dialog", "Area (ha)"))
        self.channelPercentButton.setText(_translate("Dialog", "Percent of subbasin"))
        self.reservoirBox.setToolTip(_translate("Dialog", "<html><head/><body><p>Percent of area that mus tbe water to form a reservoir for this channel. The area is the area draining to the channel if no landscape, else the floodplain of the channel.  The default setting of 101 means tht no reservoirs will be formed other than those selected during delineation.</p></body></html>"))
        self.reservoirBox.setTitle(_translate("Dialog", "Reservoir threshold"))
        self.reservoirPercent.setText(_translate("Dialog", "% water"))
        self.readChoiceGroup.setTitle(_translate("Dialog", "Read choice"))
        self.readFromPrevious.setText(_translate("Dialog", "Read from previous run"))
        self.remerge.setText(_translate("Dialog", "Re-merge short channels"))
        self.readFromMaps.setText(_translate("Dialog", "Read from maps"))
        self.generateFullHRUs.setToolTip(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Check to create and load a shapefile showing all the potential HRUs.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">You will need this file if you intend to visualise HRU results.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>"))
        self.generateFullHRUs.setText(_translate("Dialog", "Generate FullHRUs\n"
" shapefile"))
        self.optionGroup.setTitle(_translate("Dialog", "Optional"))
        self.elevBandsButton.setToolTip(_translate("Dialog", "Click to set elevation bands"))
        self.elevBandsButton.setText(_translate("Dialog", "Elevation bands"))
        self.subbasinsLabel.setText(_translate("Dialog", "Subbasins count:  "))
        self.channelsLabel.setText(_translate("Dialog", "Channels count:  "))
        self.fullHRUsLabel.setText(_translate("Dialog", "Full HRUs count:   "))
        self.progressLabel1.setText(_translate("Dialog", "dummy text        "))
        self.readButton.setToolTip(_translate("Dialog", "Read watershed, landuse, and soil data to create potential HRUs."))
        self.readButton.setText(_translate("Dialog", "Read"))
        self.HRUsTab.setTabText(self.HRUsTab.indexOf(self.tab), _translate("Dialog", "Landuse and soil"))
        self.optionGroup_2.setTitle(_translate("Dialog", "Optional"))
        self.exemptButton.setToolTip(_translate("Dialog", "Click to exempt landuses from elimination when creating multiple HRUs"))
        self.exemptButton.setText(_translate("Dialog", "Exempt landuses"))
        self.splitButton.setToolTip(_translate("Dialog", "Click to split landuses"))
        self.splitButton.setText(_translate("Dialog", "Split landuses"))
        self.hruChoiceGroup.setTitle(_translate("Dialog", "Single/Multiple HRUs"))
        self.filterAreaButton.setToolTip(_translate("Dialog", "Select to remove small HRUs by setting a minimum area threshold."))
        self.filterAreaButton.setText(_translate("Dialog", "Filter by area"))
        self.dominantHRUButton.setToolTip(_translate("Dialog", "Select to create one HRU from each subbasin, the potential HRU with the largest area in that subbasin."))
        self.dominantHRUButton.setText(_translate("Dialog", "Dominant HRU"))
        self.targetButton.setToolTip(_translate("Dialog", "Select to remove small HRUs by setting a target number of HRUs to be retained. \n"
" The smallest are removed, where smallest means smallest area in each subbasin \n"
"if the threshold method is set to area, or the smallest percentage area in each \n"
"subbasin if the threshold method is set to percentage."))
        self.targetButton.setText(_translate("Dialog", "Target number of HRUs"))
        self.filterLanduseButton.setToolTip(_translate("Dialog", "Select to remove small HRUs by setting minimum thresholds for landuse, soil, and slope band."))
        self.filterLanduseButton.setText(_translate("Dialog", "Filter by landuse, soil, slope"))
        self.dominantLanduseButton.setToolTip(_translate("Dialog", "Select to create one HRU in each subbasin, formed from the landuse, soil, and slope band \n"
"with the largest areas in that subbasin."))
        self.dominantLanduseButton.setText(_translate("Dialog", "Dominant landuse, soil, slope"))
        self.landuseSoilSlopeGroup.setTitle(_translate("Dialog", "Landuse, soil, slope thresholds"))
        self.landuseButton.setText(_translate("Dialog", "Go"))
        self.landuseMin.setText(_translate("Dialog", "0"))
        self.landuseLabel.setText(_translate("Dialog", "Landuse (%)"))
        self.landuseMax.setText(_translate("Dialog", "100"))
        self.landuseVal.setToolTip(_translate("Dialog", "Unless exempt, landuses covering a lower area or percentage of the subbasin \n"
"than this number will be eliminated from HRU creation."))
        self.soilMin.setText(_translate("Dialog", "0"))
        self.soilLabel.setText(_translate("Dialog", "Soil (%)"))
        self.soilMax.setText(_translate("Dialog", "100"))
        self.soilVal.setToolTip(_translate("Dialog", "Soils covering a lower area or percentage of the subbasin than this number \n"
"will be eliminated from HRU creation."))
        self.slopeLabel.setText(_translate("Dialog", "Slope (%)"))
        self.slopeMax.setText(_translate("Dialog", "100"))
        self.slopeVal.setToolTip(_translate("Dialog", "Slope bands covering a lower area or percentage of the subbasin than this number \n"
"will be eliminated from HRU creation."))
        self.soilButton.setText(_translate("Dialog", "Go"))
        self.slopeMin.setText(_translate("Dialog", "0"))
        self.areaGroup.setTitle(_translate("Dialog", "Area threshold"))
        self.areaMin.setText(_translate("Dialog", "0"))
        self.areaLabel.setText(_translate("Dialog", "Area (ha)"))
        self.areaMax.setText(_translate("Dialog", "9999"))
        self.areaVal.setToolTip(_translate("Dialog", "Potential HRUs (particular landuse/soil/slope band combinations) covering less than this area or percentage of their subbasin will be eliminated as HRUs."))
        self.targetGroup.setTitle(_translate("Dialog", "Target"))
        self.targetMin.setText(_translate("Dialog", "0"))
        self.targetLabel.setText(_translate("Dialog", "Number of HRUs"))
        self.targetMax.setText(_translate("Dialog", "9999"))
        self.targetVal.setToolTip(_translate("Dialog", "The target number of HRUs to be created.  The target is likely to be exceeded,\n"
"particularly when it is small or there are landuses being split or exempt from removal."))
        self.areaPercentChoiceGroup.setTitle(_translate("Dialog", "Threshold method"))
        self.percentButton.setToolTip(_translate("Dialog", "Select to interpret thresholds for landuse, soil, slope, and area as percentages of subbasin areas."))
        self.percentButton.setText(_translate("Dialog", "Percent of landscape unit"))
        self.areaButton.setToolTip(_translate("Dialog", "Select to interpret thresholds for landuse, soil, slope, and area as areas in hectares."))
        self.areaButton.setText(_translate("Dialog", "Area (Ha)"))
        self.progressLabel2.setText(_translate("Dialog", "dummy text"))
        self.createButton.setToolTip(_translate("Dialog", "Create HRUs, and exit from this form if successful."))
        self.createButton.setText(_translate("Dialog", "Create HRUs"))
        self.HRUsTab.setTabText(self.HRUsTab.indexOf(self.tab_2), _translate("Dialog", "HRUs"))
        self.cancelButton.setToolTip(_translate("Dialog", "Close this form without saving HRU data."))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))

