# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParametersDialog(object):
    def setupUi(self, ParametersDialog):
        ParametersDialog.setObjectName("ParametersDialog")
        ParametersDialog.resize(427, 357)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/swatplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ParametersDialog.setWindowIcon(icon)
        ParametersDialog.setProperty("QSWATDialog", True)
        self.gridLayout_4 = QtWidgets.QGridLayout(ParametersDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SWATPluslLabel = QtWidgets.QLabel(ParametersDialog)
        self.SWATPluslLabel.setObjectName("SWATPluslLabel")
        self.gridLayout_4.addWidget(self.SWATPluslLabel, 0, 1, 1, 2)
        self.SWATPlusButton = QtWidgets.QPushButton(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SWATPlusButton.sizePolicy().hasHeightForWidth())
        self.SWATPlusButton.setSizePolicy(sizePolicy)
        self.SWATPlusButton.setWhatsThis("")
        self.SWATPlusButton.setProperty("browseButton", True)
        self.SWATPlusButton.setObjectName("SWATPlusButton")
        self.gridLayout_4.addWidget(self.SWATPlusButton, 1, 6, 1, 1)
        self.checkUseMPI = QtWidgets.QCheckBox(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkUseMPI.sizePolicy().hasHeightForWidth())
        self.checkUseMPI.setSizePolicy(sizePolicy)
        self.checkUseMPI.setWhatsThis("")
        self.checkUseMPI.setObjectName("checkUseMPI")
        self.gridLayout_4.addWidget(self.checkUseMPI, 2, 0, 1, 1)
        self.MPILabel = QtWidgets.QLabel(ParametersDialog)
        self.MPILabel.setObjectName("MPILabel")
        self.gridLayout_4.addWidget(self.MPILabel, 2, 1, 1, 2)
        self.MPIButton = QtWidgets.QPushButton(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPIButton.sizePolicy().hasHeightForWidth())
        self.MPIButton.setSizePolicy(sizePolicy)
        self.MPIButton.setWhatsThis("")
        self.MPIButton.setProperty("browseButton", True)
        self.MPIButton.setObjectName("MPIButton")
        self.gridLayout_4.addWidget(self.MPIButton, 3, 6, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ParametersDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.widthMult = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthMult.sizePolicy().hasHeightForWidth())
        self.widthMult.setSizePolicy(sizePolicy)
        self.widthMult.setToolTip("")
        self.widthMult.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.widthMult.setObjectName("widthMult")
        self.gridLayout_2.addWidget(self.widthMult, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.widthExp = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthExp.sizePolicy().hasHeightForWidth())
        self.widthExp.setSizePolicy(sizePolicy)
        self.widthExp.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.widthExp.setObjectName("widthExp")
        self.gridLayout_2.addWidget(self.widthExp, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.depthMult = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthMult.sizePolicy().hasHeightForWidth())
        self.depthMult.setSizePolicy(sizePolicy)
        self.depthMult.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.depthMult.setObjectName("depthMult")
        self.gridLayout_2.addWidget(self.depthMult, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.depthExp = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depthExp.sizePolicy().hasHeightForWidth())
        self.depthExp.setSizePolicy(sizePolicy)
        self.depthExp.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.depthExp.setObjectName("depthExp")
        self.gridLayout_2.addWidget(self.depthExp, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 4, 0, 1, 7)
        self.groupBox_2 = QtWidgets.QGroupBox(ParametersDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.reachSlopeMultiplier = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reachSlopeMultiplier.sizePolicy().hasHeightForWidth())
        self.reachSlopeMultiplier.setSizePolicy(sizePolicy)
        self.reachSlopeMultiplier.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.reachSlopeMultiplier.setDecimals(1)
        self.reachSlopeMultiplier.setMinimum(0.1)
        self.reachSlopeMultiplier.setSingleStep(0.1)
        self.reachSlopeMultiplier.setProperty("value", 1.0)
        self.reachSlopeMultiplier.setObjectName("reachSlopeMultiplier")
        self.gridLayout.addWidget(self.reachSlopeMultiplier, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.tributarySlopeMultiplier = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tributarySlopeMultiplier.sizePolicy().hasHeightForWidth())
        self.tributarySlopeMultiplier.setSizePolicy(sizePolicy)
        self.tributarySlopeMultiplier.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.tributarySlopeMultiplier.setDecimals(1)
        self.tributarySlopeMultiplier.setMinimum(0.1)
        self.tributarySlopeMultiplier.setSingleStep(0.1)
        self.tributarySlopeMultiplier.setProperty("value", 1.0)
        self.tributarySlopeMultiplier.setObjectName("tributarySlopeMultiplier")
        self.gridLayout.addWidget(self.tributarySlopeMultiplier, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.meanSlopeMultiplier = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanSlopeMultiplier.sizePolicy().hasHeightForWidth())
        self.meanSlopeMultiplier.setSizePolicy(sizePolicy)
        self.meanSlopeMultiplier.setDecimals(1)
        self.meanSlopeMultiplier.setMinimum(0.1)
        self.meanSlopeMultiplier.setSingleStep(0.1)
        self.meanSlopeMultiplier.setProperty("value", 1.0)
        self.meanSlopeMultiplier.setObjectName("meanSlopeMultiplier")
        self.gridLayout.addWidget(self.meanSlopeMultiplier, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.mainLengthMultiplier = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainLengthMultiplier.sizePolicy().hasHeightForWidth())
        self.mainLengthMultiplier.setSizePolicy(sizePolicy)
        self.mainLengthMultiplier.setDecimals(1)
        self.mainLengthMultiplier.setMinimum(0.1)
        self.mainLengthMultiplier.setSingleStep(0.1)
        self.mainLengthMultiplier.setProperty("value", 1.0)
        self.mainLengthMultiplier.setObjectName("mainLengthMultiplier")
        self.gridLayout.addWidget(self.mainLengthMultiplier, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.tributaryLengthMultiplier = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tributaryLengthMultiplier.sizePolicy().hasHeightForWidth())
        self.tributaryLengthMultiplier.setSizePolicy(sizePolicy)
        self.tributaryLengthMultiplier.setDecimals(1)
        self.tributaryLengthMultiplier.setMinimum(0.1)
        self.tributaryLengthMultiplier.setSingleStep(0.1)
        self.tributaryLengthMultiplier.setProperty("value", 1.0)
        self.tributaryLengthMultiplier.setObjectName("tributaryLengthMultiplier")
        self.gridLayout.addWidget(self.tributaryLengthMultiplier, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 5, 0, 1, 7)
        self.label_5 = QtWidgets.QLabel(ParametersDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(ParametersDialog)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 6, 3, 1, 1)
        self.pointSizeLabel = QtWidgets.QLabel(ParametersDialog)
        self.pointSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pointSizeLabel.setObjectName("pointSizeLabel")
        self.gridLayout_4.addWidget(self.pointSizeLabel, 7, 0, 1, 1)
        self.pointSizeBox = QtWidgets.QSpinBox(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointSizeBox.sizePolicy().hasHeightForWidth())
        self.pointSizeBox.setSizePolicy(sizePolicy)
        self.pointSizeBox.setMinimum(1)
        self.pointSizeBox.setProperty("value", 10)
        self.pointSizeBox.setObjectName("pointSizeBox")
        self.gridLayout_4.addWidget(self.pointSizeBox, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 7, 2, 1, 1)
        self.saveButton = QtWidgets.QPushButton(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setProperty("okButton", True)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_4.addWidget(self.saveButton, 7, 3, 1, 2)
        self.cancelButton = QtWidgets.QPushButton(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setProperty("cancelButton", False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_4.addWidget(self.cancelButton, 7, 5, 1, 2)
        self.SWATPlusBox = QtWidgets.QLineEdit(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SWATPlusBox.sizePolicy().hasHeightForWidth())
        self.SWATPlusBox.setSizePolicy(sizePolicy)
        self.SWATPlusBox.setObjectName("SWATPlusBox")
        self.gridLayout_4.addWidget(self.SWATPlusBox, 1, 0, 1, 6)
        self.MPIBox = QtWidgets.QLineEdit(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPIBox.sizePolicy().hasHeightForWidth())
        self.MPIBox.setSizePolicy(sizePolicy)
        self.MPIBox.setObjectName("MPIBox")
        self.gridLayout_4.addWidget(self.MPIBox, 3, 0, 1, 6)
        self.burninDepth = QtWidgets.QLineEdit(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.burninDepth.sizePolicy().hasHeightForWidth())
        self.burninDepth.setSizePolicy(sizePolicy)
        self.burninDepth.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.burninDepth.setObjectName("burninDepth")
        self.gridLayout_4.addWidget(self.burninDepth, 6, 1, 1, 2)
        self.upslopeHRUDrain = QtWidgets.QLineEdit(ParametersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upslopeHRUDrain.sizePolicy().hasHeightForWidth())
        self.upslopeHRUDrain.setSizePolicy(sizePolicy)
        self.upslopeHRUDrain.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.upslopeHRUDrain.setObjectName("upslopeHRUDrain")
        self.gridLayout_4.addWidget(self.upslopeHRUDrain, 6, 4, 1, 3)
        self.label.setBuddy(self.widthMult)
        self.label_2.setBuddy(self.widthExp)
        self.label_3.setBuddy(self.depthMult)
        self.label_4.setBuddy(self.depthExp)

        self.retranslateUi(ParametersDialog)
        QtCore.QMetaObject.connectSlotsByName(ParametersDialog)

    def retranslateUi(self, ParametersDialog):
        _translate = QtCore.QCoreApplication.translate
        ParametersDialog.setWindowTitle(_translate("ParametersDialog", "QSWAT+ Parameters"))
        self.SWATPluslLabel.setToolTip(_translate("ParametersDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This is the directory where the SWAT+ Databases, Tools, ExampleDatasets and SWATPlusEditorr directories are located.  On Windows it is usually C:\\SWAT\\SWATPlus</span></p></body></html>"))
        self.SWATPluslLabel.setText(_translate("ParametersDialog", "SWATPlus directory"))
        self.SWATPlusButton.setToolTip(_translate("ParametersDialog", "Browse to select SWAT editor directory"))
        self.SWATPlusButton.setText(_translate("ParametersDialog", ". . ."))
        self.checkUseMPI.setToolTip(_translate("ParametersDialog", "If you have a multi-core processor then using the Message Passing Interface (MPI) can speed up the TauDEM programs used for watershed delineation.  If you install MP you should set this directory to where the mpiexec program is located.  On Windows this is probably C:\\Program Files\\Microsoft MPI\\Bin."))
        self.checkUseMPI.setText(_translate("ParametersDialog", "Use MPI"))
        self.MPILabel.setToolTip(_translate("ParametersDialog", "If you have a multi-core processor then using the Message Passing Interface (MPI) can speed up the TauDEM programs used for watershed delineation.  If you install MP you should set this directory to where the mpiexec program is located.  On Windows this is probably C:\\Program Files\\Microsoft MPI\\Bin."))
        self.MPILabel.setText(_translate("ParametersDialog", "MPI bin directory"))
        self.MPIButton.setToolTip(_translate("ParametersDialog", "Browse to select MPI bin directory"))
        self.MPIButton.setText(_translate("ParametersDialog", ". . ."))
        self.groupBox.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>The expression for calculating channel widths and depths (in metres) takes the form</p><p><span style=\" font-style:italic;\">Mult * A </span><span style=\" font-size:12pt; font-style:italic; vertical-align:super;\">Exp</span></p><p>where A is the drainage area in square km. <span style=\" font-style:italic;\">Mult</span> and <span style=\" font-style:italic;\">Exp</span> for width and depth may be changed here.</p><p>Changing these factors will immediately change relevant database tables. It will also affect later calculation of these tables.</p><p>Floodplain generation by buffering uses stream widths to calculate the buffer. Existing such floodplain rasters will not be affected unless the floodplain creation is rerun.<br/></p></body></html>"))
        self.groupBox.setTitle(_translate("ParametersDialog", "Channel widths and depths"))
        self.label.setText(_translate("ParametersDialog", "Channel width multiplier"))
        self.label_2.setText(_translate("ParametersDialog", "Channel width exponent"))
        self.label_3.setText(_translate("ParametersDialog", "Channel depth multiplier"))
        self.label_4.setText(_translate("ParametersDialog", "Channel depth exponent"))
        self.groupBox_2.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>Changing any of these multipliers will immediately change the current settings in the relevant database tables (if they exist), by multipying by the multiplier. It will also affect later calculation of these tables.  It will not affect the slope bands of HRUs.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("ParametersDialog", "Slope and length multipliers"))
        self.label_6.setText(_translate("ParametersDialog", "Reach slopes"))
        self.reachSlopeMultiplier.setToolTip(_translate("ParametersDialog", "All reach slopes will be multiplied by this factor."))
        self.label_7.setToolTip(_translate("ParametersDialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("ParametersDialog", "Tributary slopes"))
        self.tributarySlopeMultiplier.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>All tributary slopes will be multiplied by this factor.  This affects subbasins and landscape units (if used).</p></body></html>"))
        self.label_8.setText(_translate("ParametersDialog", "Mean slopes"))
        self.meanSlopeMultiplier.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>All mean slopes will be multiplied by this factor. This affects subbasins, landsacape units (if used) and HRUs. It also affects subbasin slope lengths.</p><p>HRUs are put into slope bands by raw slope figures from the DEM and are not affected unless the slope band limits are adjusted and the files re-read in the Create HRUs form.</p></body></html>"))
        self.label_9.setText(_translate("ParametersDialog", "Main channel length"))
        self.mainLengthMultiplier.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>All main channel lengths will be multiplied by this factor.</p><p><br/></p><p>Main channel slopes will be inversely affected.</p><p><br/></p></body></html>"))
        self.label_10.setText(_translate("ParametersDialog", "Tributary channel length"))
        self.tributaryLengthMultiplier.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>All tributary channel lengths (longest subbasin flow paths) will be multiplied by this factor.</p><p>Tributary channel slopes wil be inversely affected.</p></body></html>"))
        self.label_5.setText(_translate("ParametersDialog", "Stream burn-in depth"))
        self.label_11.setText(_translate("ParametersDialog", "Upslope HRU drain %"))
        self.pointSizeLabel.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>Change the point size of QSWATPlus forms.  This will only take effect generally when you restart QGIS, but the effect can be seen immediately in the text of this label.</p></body></html>"))
        self.pointSizeLabel.setText(_translate("ParametersDialog", "Font point size"))
        self.saveButton.setText(_translate("ParametersDialog", "Save"))
        self.cancelButton.setText(_translate("ParametersDialog", "Cancel"))
        self.burninDepth.setToolTip(_translate("ParametersDialog", "The amount in metres that DEM elevations are reduced along a \'burn-in\' stream."))
        self.upslopeHRUDrain.setToolTip(_translate("ParametersDialog", "<html><head/><body><p>The percentage of water routed from upslope HRUs that goes to the channel (or reservoir).  The remainder is routed to the floodplain landscape unit. </p></body></html>"))

from . import resources_rc
