# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_qswat.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QSwat(object):
    def setupUi(self, QSwat):
        QSwat.setObjectName("QSwat")
        QSwat.resize(391, 323)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/swatplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QSwat.setWindowIcon(icon)
        QSwat.setWhatsThis("")
        self.gridLayout_4 = QtWidgets.QGridLayout(QSwat)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(126, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.aboutButton = QtWidgets.QPushButton(QSwat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setObjectName("aboutButton")
        self.gridLayout_4.addWidget(self.aboutButton, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(QSwat)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.paramsButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsButton.sizePolicy().hasHeightForWidth())
        self.paramsButton.setSizePolicy(sizePolicy)
        self.paramsButton.setObjectName("paramsButton")
        self.gridLayout_3.addWidget(self.paramsButton, 0, 0, 1, 1)
        self.exportButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_3.addWidget(self.exportButton, 1, 0, 1, 1)
        self.reportsLabel = QtWidgets.QLabel(self.widget)
        self.reportsLabel.setObjectName("reportsLabel")
        self.gridLayout_3.addWidget(self.reportsLabel, 2, 0, 1, 1)
        self.reportsBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsBox.sizePolicy().hasHeightForWidth())
        self.reportsBox.setSizePolicy(sizePolicy)
        self.reportsBox.setDuplicatesEnabled(False)
        self.reportsBox.setObjectName("reportsBox")
        self.gridLayout_3.addWidget(self.reportsBox, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 3, 0, 2, 1)
        self.projPath = QtWidgets.QLabel(QSwat)
        self.projPath.setObjectName("projPath")
        self.gridLayout_4.addWidget(self.projPath, 5, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(QSwat)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 4, 1, 1, 2)
        self.mainBox = QtWidgets.QGroupBox(QSwat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBox.sizePolicy().hasHeightForWidth())
        self.mainBox.setSizePolicy(sizePolicy)
        self.mainBox.setObjectName("mainBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delinLabel = QtWidgets.QLabel(self.mainBox)
        self.delinLabel.setObjectName("delinLabel")
        self.gridLayout_2.addWidget(self.delinLabel, 0, 0, 1, 1)
        self.delinButton = QtWidgets.QPushButton(self.mainBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delinButton.sizePolicy().hasHeightForWidth())
        self.delinButton.setSizePolicy(sizePolicy)
        self.delinButton.setObjectName("delinButton")
        self.gridLayout_2.addWidget(self.delinButton, 0, 1, 1, 1)
        self.hrusLabel = QtWidgets.QLabel(self.mainBox)
        self.hrusLabel.setObjectName("hrusLabel")
        self.gridLayout_2.addWidget(self.hrusLabel, 1, 0, 1, 1)
        self.hrusButton = QtWidgets.QPushButton(self.mainBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hrusButton.sizePolicy().hasHeightForWidth())
        self.hrusButton.setSizePolicy(sizePolicy)
        self.hrusButton.setObjectName("hrusButton")
        self.gridLayout_2.addWidget(self.hrusButton, 1, 1, 1, 1)
        self.editLabel = QtWidgets.QLabel(self.mainBox)
        self.editLabel.setObjectName("editLabel")
        self.gridLayout_2.addWidget(self.editLabel, 2, 0, 1, 1)
        self.editButton = QtWidgets.QPushButton(self.mainBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        self.editButton.setObjectName("editButton")
        self.gridLayout_2.addWidget(self.editButton, 2, 1, 1, 1)
        self.visualiseLabel = QtWidgets.QLabel(self.mainBox)
        self.visualiseLabel.setObjectName("visualiseLabel")
        self.gridLayout_2.addWidget(self.visualiseLabel, 3, 0, 1, 1)
        self.visualiseButton = QtWidgets.QPushButton(self.mainBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualiseButton.sizePolicy().hasHeightForWidth())
        self.visualiseButton.setSizePolicy(sizePolicy)
        self.visualiseButton.setObjectName("visualiseButton")
        self.gridLayout_2.addWidget(self.visualiseButton, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.mainBox, 2, 1, 2, 2)
        self.SWATLogo = QtWidgets.QLabel(QSwat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SWATLogo.sizePolicy().hasHeightForWidth())
        self.SWATLogo.setSizePolicy(sizePolicy)
        self.SWATLogo.setMaximumSize(QtCore.QSize(170, 125))
        self.SWATLogo.setText("")
        self.SWATLogo.setPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/QSWAT-Icon/SWAT-Logo.png"))
        self.SWATLogo.setScaledContents(True)
        self.SWATLogo.setObjectName("SWATLogo")
        self.gridLayout_4.addWidget(self.SWATLogo, 0, 0, 3, 1)
        self.projectBox = QtWidgets.QGroupBox(QSwat)
        self.projectBox.setMinimumSize(QtCore.QSize(0, 50))
        self.projectBox.setObjectName("projectBox")
        self.gridLayout = QtWidgets.QGridLayout(self.projectBox)
        self.gridLayout.setObjectName("gridLayout")
        self.newButton = QtWidgets.QPushButton(self.projectBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newButton.sizePolicy().hasHeightForWidth())
        self.newButton.setSizePolicy(sizePolicy)
        self.newButton.setObjectName("newButton")
        self.gridLayout.addWidget(self.newButton, 0, 0, 1, 1)
        self.existingButton = QtWidgets.QPushButton(self.projectBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.existingButton.sizePolicy().hasHeightForWidth())
        self.existingButton.setSizePolicy(sizePolicy)
        self.existingButton.setObjectName("existingButton")
        self.gridLayout.addWidget(self.existingButton, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.projectBox, 1, 1, 1, 2)
        self.delinLabel.setBuddy(self.delinButton)
        self.hrusLabel.setBuddy(self.hrusButton)
        self.editLabel.setBuddy(self.editButton)
        self.visualiseLabel.setBuddy(self.visualiseButton)

        self.retranslateUi(QSwat)
        self.buttonBox.accepted.connect(QSwat.accept)
        self.buttonBox.rejected.connect(QSwat.reject)
        QtCore.QMetaObject.connectSlotsByName(QSwat)

    def retranslateUi(self, QSwat):
        _translate = QtCore.QCoreApplication.translate
        QSwat.setWindowTitle(_translate("QSwat", "QSWAT+"))
        self.aboutButton.setText(_translate("QSwat", "About"))
        self.paramsButton.setToolTip(_translate("QSwat", "<html><head/><body><p>Click to set the location of the SWATPlusr and (optionally) MPI.  Unless these locations change, you only need to do this once; the values are used for all projects.</p><p><br/></p><p>A number of other parameters may be set here, which are project specific.</p></body></html>"))
        self.paramsButton.setText(_translate("QSwat", "QSWAT+ Parameters"))
        self.exportButton.setToolTip(_translate("QSwat", "<html><head/><body><p>Export SQLite database table to a csv file.</p></body></html>"))
        self.exportButton.setText(_translate("QSwat", "Export Table"))
        self.reportsLabel.setText(_translate("QSwat", "Reports"))
        self.projPath.setText(_translate("QSwat", "This is the path to the  project"))
        self.mainBox.setTitle(_translate("QSwat", "Main Steps"))
        self.delinLabel.setText(_translate("QSwat", "Step 1"))
        self.delinButton.setToolTip(_translate("QSwat", "Click to select the DEM and delineate the watershed"))
        self.delinButton.setText(_translate("QSwat", "Delineate Watershed"))
        self.hrusLabel.setText(_translate("QSwat", "Step 2"))
        self.hrusButton.setToolTip(_translate("QSwat", "Click to select landuse and soil files and create HRUs"))
        self.hrusButton.setText(_translate("QSwat", "Create HRUs"))
        self.editLabel.setText(_translate("QSwat", "Step 3"))
        self.editButton.setToolTip(_translate("QSwat", "Click to run the SWAT+ editor"))
        self.editButton.setText(_translate("QSwat", "Edit Inputs and Run SWAT+"))
        self.visualiseLabel.setText(_translate("QSwat", "Step 4"))
        self.visualiseButton.setToolTip(_translate("QSwat", "Click to visualise outputs after a SWAT run"))
        self.visualiseButton.setText(_translate("QSwat", "Visualise"))
        self.projectBox.setTitle(_translate("QSwat", "Select Project"))
        self.newButton.setText(_translate("QSwat", "New Project"))
        self.existingButton.setText(_translate("QSwat", "Existing Project"))

from . import resources_rc
