# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_split.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SplitDialog(object):
    def setupUi(self, SplitDialog):
        SplitDialog.setObjectName("SplitDialog")
        SplitDialog.resize(336, 270)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/swatplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SplitDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SplitDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(SplitDialog)
        self.label_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SplitDialog)
        self.label_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 3)
        self.newCombo = QtWidgets.QComboBox(SplitDialog)
        self.newCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.newCombo.setObjectName("newCombo")
        self.gridLayout.addWidget(self.newCombo, 2, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 3, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(SplitDialog)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        self.table.setRowCount(0)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setDefaultSectionSize(75)
        self.table.horizontalHeader().setMinimumSectionSize(20)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(20)
        self.table.verticalHeader().setMinimumSectionSize(19)
        self.gridLayout.addWidget(self.table, 3, 2, 3, 3)
        self.deleteButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 4, 0, 1, 1)
        self.deleteSplitButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteSplitButton.sizePolicy().hasHeightForWidth())
        self.deleteSplitButton.setSizePolicy(sizePolicy)
        self.deleteSplitButton.setObjectName("deleteSplitButton")
        self.gridLayout.addWidget(self.deleteSplitButton, 5, 0, 1, 1)
        self.cancelEditButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelEditButton.sizePolicy().hasHeightForWidth())
        self.cancelEditButton.setSizePolicy(sizePolicy)
        self.cancelEditButton.setObjectName("cancelEditButton")
        self.gridLayout.addWidget(self.cancelEditButton, 6, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 7, 4, 1, 1)
        self.splitCombo = QtWidgets.QComboBox(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitCombo.sizePolicy().hasHeightForWidth())
        self.splitCombo.setSizePolicy(sizePolicy)
        self.splitCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.splitCombo.setObjectName("splitCombo")
        self.gridLayout.addWidget(self.splitCombo, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.saveEditButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveEditButton.sizePolicy().hasHeightForWidth())
        self.saveEditButton.setSizePolicy(sizePolicy)
        self.saveEditButton.setObjectName("saveEditButton")
        self.gridLayout.addWidget(self.saveEditButton, 6, 3, 1, 1)
        self.saveSplitsButton = QtWidgets.QPushButton(SplitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSplitsButton.sizePolicy().hasHeightForWidth())
        self.saveSplitsButton.setSizePolicy(sizePolicy)
        self.saveSplitsButton.setObjectName("saveSplitsButton")
        self.gridLayout.addWidget(self.saveSplitsButton, 7, 3, 1, 1)

        self.retranslateUi(SplitDialog)
        QtCore.QMetaObject.connectSlotsByName(SplitDialog)

    def retranslateUi(self, SplitDialog):
        _translate = QtCore.QCoreApplication.translate
        SplitDialog.setWindowTitle(_translate("SplitDialog", "Split Landuses"))
        self.label_2.setText(_translate("SplitDialog", "Select landuse\n"
"to split"))
        self.label_3.setText(_translate("SplitDialog", "Select split landuse\n"
"to edit"))
        self.addButton.setToolTip(_translate("SplitDialog", "Add a sub-landuse to the split in the table."))
        self.addButton.setText(_translate("SplitDialog", "Add\n"
"sub-landuse"))
        self.deleteButton.setToolTip(_translate("SplitDialog", "Remove the selected row from the table.  You can select a row by clicking in the table."))
        self.deleteButton.setText(_translate("SplitDialog", "Delete\n"
"sub-landuse"))
        self.deleteSplitButton.setToolTip(_translate("SplitDialog", "Clear the table and remove the split from the current list of landuses to split."))
        self.deleteSplitButton.setText(_translate("SplitDialog", "Delete\n"
"split landuse"))
        self.cancelEditButton.setToolTip(_translate("SplitDialog", "Clear the table."))
        self.cancelEditButton.setText(_translate("SplitDialog", "Cancel\n"
"edits"))
        self.cancelButton.setToolTip(_translate("SplitDialog", "Leave the set of panduses to spliut as they were when this form was opened and exit."))
        self.cancelButton.setText(_translate("SplitDialog", "Cancel"))
        self.saveEditButton.setToolTip(_translate("SplitDialog", "Save the table as a landuse to be split.  You must edit the percentages first so they sum to 100."))
        self.saveEditButton.setText(_translate("SplitDialog", "Save\n"
"edits"))
        self.saveSplitsButton.setToolTip(_translate("SplitDialog", "Save the current set of split landuses and exit."))
        self.saveSplitsButton.setText(_translate("SplitDialog", "Save\n"
"splits"))

from . import resources_rc
