# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Users/Public/QSWATPlus3/QSWATPlus\ui_visualise.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VisualiseDialog(object):
    def setupUi(self, VisualiseDialog):
        VisualiseDialog.setObjectName("VisualiseDialog")
        VisualiseDialog.resize(470, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VisualiseDialog.sizePolicy().hasHeightForWidth())
        VisualiseDialog.setSizePolicy(sizePolicy)
        VisualiseDialog.setMinimumSize(QtCore.QSize(0, 0))
        VisualiseDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/swatplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VisualiseDialog.setWindowIcon(icon)
        self.gridLayout_17 = QtWidgets.QGridLayout(VisualiseDialog)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widget = QtWidgets.QWidget(VisualiseDialog)
        self.widget.setObjectName("widget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.scenarioBox = QtWidgets.QGroupBox(self.widget)
        self.scenarioBox.setObjectName("scenarioBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scenarioBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scenariosCombo = QtWidgets.QComboBox(self.scenarioBox)
        self.scenariosCombo.setMinimumSize(QtCore.QSize(126, 0))
        self.scenariosCombo.setObjectName("scenariosCombo")
        self.gridLayout_5.addWidget(self.scenariosCombo, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.scenarioBox, 0, 0, 1, 1)
        self.outputBox = QtWidgets.QGroupBox(self.widget)
        self.outputBox.setObjectName("outputBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.outputBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.outputCombo = QtWidgets.QComboBox(self.outputBox)
        self.outputCombo.setMinimumSize(QtCore.QSize(126, 0))
        self.outputCombo.setObjectName("outputCombo")
        self.gridLayout_6.addWidget(self.outputCombo, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.outputBox, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(421, 391))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.staticTab = QtWidgets.QWidget()
        self.staticTab.setObjectName("staticTab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.staticTab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.resultsFileBox = QtWidgets.QGroupBox(self.staticTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsFileBox.sizePolicy().hasHeightForWidth())
        self.resultsFileBox.setSizePolicy(sizePolicy)
        self.resultsFileBox.setObjectName("resultsFileBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.resultsFileBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.resultsFileEdit = QtWidgets.QLineEdit(self.resultsFileBox)
        self.resultsFileEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.resultsFileEdit.setObjectName("resultsFileEdit")
        self.gridLayout_8.addWidget(self.resultsFileEdit, 0, 0, 1, 1)
        self.resultsFileButton = QtWidgets.QPushButton(self.resultsFileBox)
        self.resultsFileButton.setObjectName("resultsFileButton")
        self.gridLayout_8.addWidget(self.resultsFileButton, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.resultsFileBox, 0, 0, 1, 2)
        self.variablesBox = QtWidgets.QGroupBox(self.staticTab)
        self.variablesBox.setObjectName("variablesBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.variablesBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.variableCombo = QtWidgets.QComboBox(self.variablesBox)
        self.variableCombo.setObjectName("variableCombo")
        self.gridLayout_15.addWidget(self.variableCombo, 0, 1, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.variablesBox)
        self.addButton.setObjectName("addButton")
        self.gridLayout_15.addWidget(self.addButton, 1, 0, 1, 1)
        self.variableList = QtWidgets.QListWidget(self.variablesBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.variableList.setFont(font)
        self.variableList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.variableList.setProperty("showDropIndicator", False)
        self.variableList.setObjectName("variableList")
        self.gridLayout_15.addWidget(self.variableList, 1, 1, 4, 1)
        self.allButton = QtWidgets.QPushButton(self.variablesBox)
        self.allButton.setObjectName("allButton")
        self.gridLayout_15.addWidget(self.allButton, 2, 0, 1, 1)
        self.delButton = QtWidgets.QPushButton(self.variablesBox)
        self.delButton.setObjectName("delButton")
        self.gridLayout_15.addWidget(self.delButton, 3, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.variablesBox)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_15.addWidget(self.clearButton, 4, 0, 1, 1)
        self.gridLayout_16.addWidget(self.variablesBox, 1, 0, 3, 1)
        self.summaryBox = QtWidgets.QGroupBox(self.staticTab)
        self.summaryBox.setObjectName("summaryBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.summaryBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.summaryCombo = QtWidgets.QComboBox(self.summaryBox)
        self.summaryCombo.setMinimumSize(QtCore.QSize(126, 0))
        self.summaryCombo.setObjectName("summaryCombo")
        self.gridLayout_14.addWidget(self.summaryCombo, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.summaryBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 126, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 2, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.staticTab)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_16.addWidget(self.saveButton, 3, 1, 1, 1)
        self.printGroup = QtWidgets.QGroupBox(self.staticTab)
        self.printGroup.setObjectName("printGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.printGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.landscapeButton = QtWidgets.QRadioButton(self.printGroup)
        self.landscapeButton.setChecked(True)
        self.landscapeButton.setObjectName("landscapeButton")
        self.gridLayout_4.addWidget(self.landscapeButton, 0, 0, 1, 1)
        self.portraitButton = QtWidgets.QRadioButton(self.printGroup)
        self.portraitButton.setObjectName("portraitButton")
        self.gridLayout_4.addWidget(self.portraitButton, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.printGroup)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 2, 1, 1)
        self.printCount = QtWidgets.QSpinBox(self.printGroup)
        self.printCount.setMinimum(1)
        self.printCount.setMaximum(6)
        self.printCount.setObjectName("printCount")
        self.gridLayout_4.addWidget(self.printCount, 0, 3, 1, 1)
        self.printButton = QtWidgets.QPushButton(self.printGroup)
        self.printButton.setObjectName("printButton")
        self.gridLayout_4.addWidget(self.printButton, 0, 4, 1, 1)
        self.gridLayout_16.addWidget(self.printGroup, 4, 0, 1, 2)
        self.tabWidget.addTab(self.staticTab, "")
        self.animationTab = QtWidgets.QWidget()
        self.animationTab.setObjectName("animationTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.animationTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.calculateLabel = QtWidgets.QLabel(self.animationTab)
        self.calculateLabel.setText("")
        self.calculateLabel.setObjectName("calculateLabel")
        self.gridLayout_9.addWidget(self.calculateLabel, 1, 2, 1, 1)
        self.composeOptions = QtWidgets.QGroupBox(self.animationTab)
        self.composeOptions.setObjectName("composeOptions")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.composeOptions)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.composeLandscape = QtWidgets.QRadioButton(self.composeOptions)
        self.composeLandscape.setChecked(True)
        self.composeLandscape.setObjectName("composeLandscape")
        self.horizontalLayout_3.addWidget(self.composeLandscape)
        self.composePortrait = QtWidgets.QRadioButton(self.composeOptions)
        self.composePortrait.setObjectName("composePortrait")
        self.horizontalLayout_3.addWidget(self.composePortrait)
        self.label_16 = QtWidgets.QLabel(self.composeOptions)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.composeCount = QtWidgets.QSpinBox(self.composeOptions)
        self.composeCount.setMinimum(1)
        self.composeCount.setMaximum(6)
        self.composeCount.setObjectName("composeCount")
        self.horizontalLayout_3.addWidget(self.composeCount)
        self.gridLayout_9.addWidget(self.composeOptions, 2, 0, 1, 8)
        spacerItem1 = QtWidgets.QSpacerItem(233, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 3, 0, 1, 6)
        self.playCommand = QtWidgets.QCommandLinkButton(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playCommand.sizePolicy().hasHeightForWidth())
        self.playCommand.setSizePolicy(sizePolicy)
        self.playCommand.setMinimumSize(QtCore.QSize(41, 41))
        self.playCommand.setMaximumSize(QtCore.QSize(41, 41))
        self.playCommand.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/play-24x24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playCommand.setIcon(icon1)
        self.playCommand.setIconSize(QtCore.QSize(24, 24))
        self.playCommand.setObjectName("playCommand")
        self.gridLayout_9.addWidget(self.playCommand, 3, 6, 1, 1)
        self.pauseCommand = QtWidgets.QCommandLinkButton(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseCommand.sizePolicy().hasHeightForWidth())
        self.pauseCommand.setSizePolicy(sizePolicy)
        self.pauseCommand.setMinimumSize(QtCore.QSize(41, 41))
        self.pauseCommand.setMaximumSize(QtCore.QSize(41, 41))
        self.pauseCommand.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/pause-24x24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseCommand.setIcon(icon2)
        self.pauseCommand.setIconSize(QtCore.QSize(24, 24))
        self.pauseCommand.setObjectName("pauseCommand")
        self.gridLayout_9.addWidget(self.pauseCommand, 3, 7, 1, 1)
        self.rewindCommand = QtWidgets.QCommandLinkButton(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewindCommand.sizePolicy().hasHeightForWidth())
        self.rewindCommand.setSizePolicy(sizePolicy)
        self.rewindCommand.setMinimumSize(QtCore.QSize(41, 41))
        self.rewindCommand.setMaximumSize(QtCore.QSize(41, 41))
        self.rewindCommand.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/QSWATPlus/rewind-24x24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindCommand.setIcon(icon3)
        self.rewindCommand.setIconSize(QtCore.QSize(24, 24))
        self.rewindCommand.setObjectName("rewindCommand")
        self.gridLayout_9.addWidget(self.rewindCommand, 3, 8, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.animationTab)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout_9.addWidget(self.dateLabel, 4, 0, 1, 9)
        self.slider = QtWidgets.QSlider(self.animationTab)
        self.slider.setMinimum(1)
        self.slider.setSliderPosition(1)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider.setObjectName("slider")
        self.gridLayout_9.addWidget(self.slider, 5, 0, 1, 9)
        self.label = QtWidgets.QLabel(self.animationTab)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 6, 7, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.animationTab)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_9.addWidget(self.spinBox, 6, 8, 1, 1)
        self.recordLabel = QtWidgets.QLabel(self.animationTab)
        self.recordLabel.setObjectName("recordLabel")
        self.gridLayout_9.addWidget(self.recordLabel, 7, 1, 1, 3)
        self.playButton = QtWidgets.QPushButton(self.animationTab)
        self.playButton.setFlat(False)
        self.playButton.setObjectName("playButton")
        self.gridLayout_9.addWidget(self.playButton, 7, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.animationTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 7, 5, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.canvasAnimation = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasAnimation.sizePolicy().hasHeightForWidth())
        self.canvasAnimation.setSizePolicy(sizePolicy)
        self.canvasAnimation.setChecked(True)
        self.canvasAnimation.setObjectName("canvasAnimation")
        self.gridLayout_22.addWidget(self.canvasAnimation, 0, 0, 1, 1)
        self.printAnimation = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printAnimation.sizePolicy().hasHeightForWidth())
        self.printAnimation.setSizePolicy(sizePolicy)
        self.printAnimation.setObjectName("printAnimation")
        self.gridLayout_22.addWidget(self.printAnimation, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(91, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 1, 0, 1, 2)
        self.animationSetup = QtWidgets.QGroupBox(self.animationTab)
        self.animationSetup.setMinimumSize(QtCore.QSize(0, 0))
        self.animationSetup.setObjectName("animationSetup")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.animationSetup)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.newAnimation = QtWidgets.QRadioButton(self.animationSetup)
        self.newAnimation.setChecked(True)
        self.newAnimation.setObjectName("newAnimation")
        self.gridLayout_10.addWidget(self.newAnimation, 0, 0, 1, 1)
        self.currentAnimation = QtWidgets.QRadioButton(self.animationSetup)
        self.currentAnimation.setObjectName("currentAnimation")
        self.gridLayout_10.addWidget(self.currentAnimation, 0, 1, 1, 1)
        self.animationVariableCombo = QtWidgets.QComboBox(self.animationSetup)
        self.animationVariableCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.animationVariableCombo.setObjectName("animationVariableCombo")
        self.gridLayout_10.addWidget(self.animationVariableCombo, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.animationSetup)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.animationSetup, 0, 0, 1, 9)
        self.recordButton = QtWidgets.QPushButton(self.animationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setMinimumSize(QtCore.QSize(40, 25))
        self.recordButton.setStyleSheet("background-color: green; border: none;")
        self.recordButton.setText("")
        self.recordButton.setObjectName("recordButton")
        self.gridLayout_9.addWidget(self.recordButton, 7, 0, 1, 1)
        self.tabWidget.addTab(self.animationTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.observedFileBox = QtWidgets.QGroupBox(self.tab)
        self.observedFileBox.setObjectName("observedFileBox")
        self.gridLayout = QtWidgets.QGridLayout(self.observedFileBox)
        self.gridLayout.setObjectName("gridLayout")
        self.observedFileEdit = QtWidgets.QLineEdit(self.observedFileBox)
        self.observedFileEdit.setObjectName("observedFileEdit")
        self.gridLayout.addWidget(self.observedFileEdit, 0, 0, 1, 1)
        self.observedFileButton = QtWidgets.QPushButton(self.observedFileBox)
        self.observedFileButton.setObjectName("observedFileButton")
        self.gridLayout.addWidget(self.observedFileButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.observedFileBox, 0, 0, 1, 6)
        self.unitPlot = QtWidgets.QComboBox(self.tab)
        self.unitPlot.setObjectName("unitPlot")
        self.gridLayout_3.addWidget(self.unitPlot, 2, 1, 1, 1)
        self.unitEdit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitEdit.sizePolicy().hasHeightForWidth())
        self.unitEdit.setSizePolicy(sizePolicy)
        self.unitEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unitEdit.setObjectName("unitEdit")
        self.gridLayout_3.addWidget(self.unitEdit, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 3, 1, 1)
        self.variablePlot = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variablePlot.sizePolicy().hasHeightForWidth())
        self.variablePlot.setSizePolicy(sizePolicy)
        self.variablePlot.setObjectName("variablePlot")
        self.gridLayout_3.addWidget(self.variablePlot, 2, 4, 1, 2)
        self.addPlot = QtWidgets.QPushButton(self.tab)
        self.addPlot.setObjectName("addPlot")
        self.gridLayout_3.addWidget(self.addPlot, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(23)
        self.gridLayout_3.addWidget(self.tableWidget, 3, 1, 6, 5)
        self.deletePlot = QtWidgets.QPushButton(self.tab)
        self.deletePlot.setObjectName("deletePlot")
        self.gridLayout_3.addWidget(self.deletePlot, 4, 0, 1, 1)
        self.copyPlot = QtWidgets.QPushButton(self.tab)
        self.copyPlot.setObjectName("copyPlot")
        self.gridLayout_3.addWidget(self.copyPlot, 5, 0, 1, 1)
        self.upPlot = QtWidgets.QPushButton(self.tab)
        self.upPlot.setObjectName("upPlot")
        self.gridLayout_3.addWidget(self.upPlot, 6, 0, 1, 1)
        self.downPlot = QtWidgets.QPushButton(self.tab)
        self.downPlot.setObjectName("downPlot")
        self.gridLayout_3.addWidget(self.downPlot, 7, 0, 1, 1)
        self.addObserved = QtWidgets.QPushButton(self.tab)
        self.addObserved.setObjectName("addObserved")
        self.gridLayout_3.addWidget(self.addObserved, 8, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 9, 0, 1, 5)
        self.plotButton = QtWidgets.QPushButton(self.tab)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout_3.addWidget(self.plotButton, 9, 5, 1, 1)
        self.unitLabel = QtWidgets.QLabel(self.tab)
        self.unitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLabel.setObjectName("unitLabel")
        self.gridLayout_3.addWidget(self.unitLabel, 1, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 4, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.QtabWidget = QtWidgets.QTabWidget(self.tab_2)
        self.QtabWidget.setObjectName("QtabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.QqSpin = QtWidgets.QSpinBox(self.tab_3)
        self.QqSpin.setMaximum(100)
        self.QqSpin.setProperty("value", 95)
        self.QqSpin.setObjectName("QqSpin")
        self.gridLayout_11.addWidget(self.QqSpin, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 2, 0, 1, 1)
        self.QqResults = QtWidgets.QTableWidget(self.tab_3)
        self.QqResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.QqResults.setProperty("showDropIndicator", False)
        self.QqResults.setDragDropOverwriteMode(False)
        self.QqResults.setWordWrap(False)
        self.QqResults.setCornerButtonEnabled(False)
        self.QqResults.setRowCount(12)
        self.QqResults.setColumnCount(1)
        self.QqResults.setObjectName("QqResults")
        self.QqResults.horizontalHeader().setVisible(False)
        self.QqResults.horizontalHeader().setDefaultSectionSize(100)
        self.QqResults.horizontalHeader().setHighlightSections(False)
        self.QqResults.horizontalHeader().setMinimumSectionSize(50)
        self.QqResults.verticalHeader().setVisible(False)
        self.QqResults.verticalHeader().setDefaultSectionSize(18)
        self.QqResults.verticalHeader().setMinimumSectionSize(18)
        self.gridLayout_11.addWidget(self.QqResults, 2, 2, 5, 1)
        self.QqSubbasin = QtWidgets.QComboBox(self.tab_3)
        self.QqSubbasin.setObjectName("QqSubbasin")
        self.gridLayout_11.addWidget(self.QqSubbasin, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem5, 4, 0, 1, 1)
        self.QqCalculate = QtWidgets.QPushButton(self.tab_3)
        self.QqCalculate.setObjectName("QqCalculate")
        self.gridLayout_11.addWidget(self.QqCalculate, 5, 0, 1, 1)
        self.QqSave = QtWidgets.QPushButton(self.tab_3)
        self.QqSave.setObjectName("QqSave")
        self.gridLayout_11.addWidget(self.QqSave, 6, 0, 1, 1)
        self.QqAppend = QtWidgets.QCheckBox(self.tab_3)
        self.QqAppend.setObjectName("QqAppend")
        self.gridLayout_11.addWidget(self.QqAppend, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 3)
        self.QtabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_19.addWidget(self.label_18, 0, 0, 1, 4)
        self.dQpSpinD = QtWidgets.QSpinBox(self.tab_4)
        self.dQpSpinD.setMinimum(2)
        self.dQpSpinD.setMaximum(365)
        self.dQpSpinD.setProperty("value", 21)
        self.dQpSpinD.setObjectName("dQpSpinD")
        self.gridLayout_19.addWidget(self.dQpSpinD, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(114, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem6, 1, 1, 1, 2)
        self.dQpCalculate = QtWidgets.QPushButton(self.tab_4)
        self.dQpCalculate.setObjectName("dQpCalculate")
        self.gridLayout_19.addWidget(self.dQpCalculate, 1, 3, 1, 2)
        self.dQpSpinP = QtWidgets.QSpinBox(self.tab_4)
        self.dQpSpinP.setMaximum(100)
        self.dQpSpinP.setProperty("value", 5)
        self.dQpSpinP.setObjectName("dQpSpinP")
        self.gridLayout_19.addWidget(self.dQpSpinP, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem7, 3, 1, 1, 2)
        self.dQpResult = QtWidgets.QLabel(self.tab_4)
        self.dQpResult.setObjectName("dQpResult")
        self.gridLayout_19.addWidget(self.dQpResult, 3, 3, 1, 3)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_19.addWidget(self.label_20, 4, 0, 1, 3)
        self.dQpSubbasin = QtWidgets.QComboBox(self.tab_4)
        self.dQpSubbasin.setObjectName("dQpSubbasin")
        self.gridLayout_19.addWidget(self.dQpSubbasin, 5, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(108, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem8, 5, 2, 1, 1)
        self.dQpSave = QtWidgets.QPushButton(self.tab_4)
        self.dQpSave.setObjectName("dQpSave")
        self.gridLayout_19.addWidget(self.dQpSave, 5, 3, 1, 2)
        self.dQpAppend = QtWidgets.QCheckBox(self.tab_4)
        self.dQpAppend.setObjectName("dQpAppend")
        self.gridLayout_19.addWidget(self.dQpAppend, 5, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(32, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem9, 7, 4, 5, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_19.addWidget(self.label_21, 6, 0, 1, 1)
        self.dQpStartMonth = QtWidgets.QComboBox(self.tab_4)
        self.dQpStartMonth.setObjectName("dQpStartMonth")
        self.gridLayout_19.addWidget(self.dQpStartMonth, 7, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.dQpPercentile = QtWidgets.QRadioButton(self.groupBox_2)
        self.dQpPercentile.setChecked(True)
        self.dQpPercentile.setObjectName("dQpPercentile")
        self.gridLayout_21.addWidget(self.dQpPercentile, 0, 0, 1, 1)
        self.dQpMean = QtWidgets.QRadioButton(self.groupBox_2)
        self.dQpMean.setObjectName("dQpMean")
        self.gridLayout_21.addWidget(self.dQpMean, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_2, 8, 0, 4, 2)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_19.addWidget(self.label_19, 2, 0, 1, 5)
        self.QtabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_20.addWidget(self.label_23, 0, 0, 1, 1)
        self.QbAnnualResult = QtWidgets.QLabel(self.tab_5)
        self.QbAnnualResult.setObjectName("QbAnnualResult")
        self.gridLayout_20.addWidget(self.QbAnnualResult, 0, 2, 1, 1)
        self.QbSubbasin = QtWidgets.QComboBox(self.tab_5)
        self.QbSubbasin.setObjectName("QbSubbasin")
        self.gridLayout_20.addWidget(self.QbSubbasin, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_20.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_20.addWidget(self.label_24, 2, 0, 1, 2)
        self.QbResults = QtWidgets.QTableWidget(self.tab_5)
        self.QbResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.QbResults.setProperty("showDropIndicator", False)
        self.QbResults.setDragDropOverwriteMode(False)
        self.QbResults.setWordWrap(False)
        self.QbResults.setCornerButtonEnabled(False)
        self.QbResults.setRowCount(12)
        self.QbResults.setColumnCount(1)
        self.QbResults.setObjectName("QbResults")
        self.QbResults.horizontalHeader().setVisible(False)
        self.QbResults.horizontalHeader().setDefaultSectionSize(100)
        self.QbResults.horizontalHeader().setHighlightSections(False)
        self.QbResults.horizontalHeader().setMinimumSectionSize(50)
        self.QbResults.verticalHeader().setVisible(False)
        self.QbResults.verticalHeader().setDefaultSectionSize(18)
        self.QbResults.verticalHeader().setMinimumSectionSize(18)
        self.gridLayout_20.addWidget(self.QbResults, 2, 2, 5, 1)
        self.QbStartMonth = QtWidgets.QComboBox(self.tab_5)
        self.QbStartMonth.setObjectName("QbStartMonth")
        self.gridLayout_20.addWidget(self.QbStartMonth, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem10, 4, 0, 1, 1)
        self.QbCalculate = QtWidgets.QPushButton(self.tab_5)
        self.QbCalculate.setMinimumSize(QtCore.QSize(92, 0))
        self.QbCalculate.setObjectName("QbCalculate")
        self.gridLayout_20.addWidget(self.QbCalculate, 5, 0, 1, 1)
        self.QbSave = QtWidgets.QPushButton(self.tab_5)
        self.QbSave.setObjectName("QbSave")
        self.gridLayout_20.addWidget(self.QbSave, 6, 0, 1, 1)
        self.QbAppend = QtWidgets.QCheckBox(self.tab_5)
        self.QbAppend.setObjectName("QbAppend")
        self.gridLayout_20.addWidget(self.QbAppend, 6, 1, 1, 1)
        self.QtabWidget.addTab(self.tab_5, "")
        self.gridLayout_18.addWidget(self.QtabWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_3, 2, 0, 1, 2)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(321, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 0, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.widget_2)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_7.addWidget(self.closeButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.widget_2, 3, 0, 1, 2)
        self.periodBox = QtWidgets.QGroupBox(self.widget)
        self.periodBox.setObjectName("periodBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.periodBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.periodBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 3)
        self.startDay = QtWidgets.QComboBox(self.periodBox)
        self.startDay.setMaxVisibleItems(31)
        self.startDay.setObjectName("startDay")
        self.gridLayout_2.addWidget(self.startDay, 1, 0, 1, 1)
        self.startMonth = QtWidgets.QComboBox(self.periodBox)
        self.startMonth.setMaxVisibleItems(12)
        self.startMonth.setObjectName("startMonth")
        self.gridLayout_2.addWidget(self.startMonth, 1, 1, 1, 1)
        self.startYear = QtWidgets.QLineEdit(self.periodBox)
        self.startYear.setInputMethodHints(QtCore.Qt.ImhNone)
        self.startYear.setObjectName("startYear")
        self.gridLayout_2.addWidget(self.startYear, 1, 2, 1, 1)
        self.finishDay = QtWidgets.QComboBox(self.periodBox)
        self.finishDay.setMaxVisibleItems(31)
        self.finishDay.setObjectName("finishDay")
        self.gridLayout_2.addWidget(self.finishDay, 1, 3, 1, 1)
        self.finishMonth = QtWidgets.QComboBox(self.periodBox)
        self.finishMonth.setMaxVisibleItems(12)
        self.finishMonth.setObjectName("finishMonth")
        self.gridLayout_2.addWidget(self.finishMonth, 1, 4, 1, 1)
        self.finishYear = QtWidgets.QLineEdit(self.periodBox)
        self.finishYear.setInputMethodHints(QtCore.Qt.ImhNone)
        self.finishYear.setObjectName("finishYear")
        self.gridLayout_2.addWidget(self.finishYear, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.periodBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.periodBox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.periodBox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.periodBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.periodBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.periodBox)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.periodBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 3)
        self.gridLayout_13.addWidget(self.periodBox, 1, 0, 1, 2)
        self.gridLayout_17.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(VisualiseDialog)
        self.tabWidget.setCurrentIndex(1)
        self.QtabWidget.setCurrentIndex(0)
        self.finishMonth.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(VisualiseDialog)

    def retranslateUi(self, VisualiseDialog):
        _translate = QtCore.QCoreApplication.translate
        VisualiseDialog.setWindowTitle(_translate("VisualiseDialog", "Visualise Results"))
        self.scenarioBox.setTitle(_translate("VisualiseDialog", "Choose scenario"))
        self.outputBox.setTitle(_translate("VisualiseDialog", "Choose SWAT+ output table"))
        self.resultsFileBox.setTitle(_translate("VisualiseDialog", "Choose results shapefile"))
        self.resultsFileButton.setText(_translate("VisualiseDialog", "..."))
        self.variablesBox.setTitle(_translate("VisualiseDialog", "Choose variables"))
        self.variableCombo.setToolTip(_translate("VisualiseDialog", "Select variable to be added to list."))
        self.addButton.setToolTip(_translate("VisualiseDialog", "Add chosen variable to list."))
        self.addButton.setText(_translate("VisualiseDialog", "Add"))
        self.allButton.setToolTip(_translate("VisualiseDialog", "Add all variables in current output table to list"))
        self.allButton.setText(_translate("VisualiseDialog", "All"))
        self.delButton.setToolTip(_translate("VisualiseDialog", "Delete selected variable from list."))
        self.delButton.setText(_translate("VisualiseDialog", "Del"))
        self.clearButton.setToolTip(_translate("VisualiseDialog", "Remove all variables from the list."))
        self.clearButton.setText(_translate("VisualiseDialog", "Clear"))
        self.summaryBox.setTitle(_translate("VisualiseDialog", "Choose summary"))
        self.saveButton.setToolTip(_translate("VisualiseDialog", "Write data to results shapefile and display summary values for selected variable."))
        self.saveButton.setText(_translate("VisualiseDialog", "Create"))
        self.printGroup.setTitle(_translate("VisualiseDialog", "Print"))
        self.landscapeButton.setText(_translate("VisualiseDialog", "Landscape"))
        self.portraitButton.setText(_translate("VisualiseDialog", "Portrait"))
        self.label_15.setText(_translate("VisualiseDialog", "Number of maps"))
        self.printButton.setToolTip(_translate("VisualiseDialog", "Create print composition."))
        self.printButton.setText(_translate("VisualiseDialog", "Print"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.staticTab), _translate("VisualiseDialog", "Static data"))
        self.composeOptions.setTitle(_translate("VisualiseDialog", "Composer options"))
        self.composeLandscape.setText(_translate("VisualiseDialog", "Landscape"))
        self.composePortrait.setText(_translate("VisualiseDialog", "Portrait"))
        self.label_16.setText(_translate("VisualiseDialog", "Number of maps"))
        self.playCommand.setToolTip(_translate("VisualiseDialog", "Start button"))
        self.pauseCommand.setToolTip(_translate("VisualiseDialog", "Pause button"))
        self.rewindCommand.setToolTip(_translate("VisualiseDialog", "Rewind button"))
        self.dateLabel.setText(_translate("VisualiseDialog", "Date"))
        self.slider.setToolTip(_translate("VisualiseDialog", "Slider to control currently diplayed date and data.  \n"
"Slider may be driven automatically at set speed by clicking start button. \n"
"Can also be controlled manually by dragging or by using left and right arrows on keyboard."))
        self.label.setText(_translate("VisualiseDialog", "Speed"))
        self.spinBox.setToolTip(_translate("VisualiseDialog", "Change speed of animation.  Larger numbers mean increased speed."))
        self.recordLabel.setText(_translate("VisualiseDialog", "Start recording"))
        self.playButton.setText(_translate("VisualiseDialog", "Play"))
        self.label_14.setText(_translate("VisualiseDialog", "Play recording"))
        self.groupBox.setTitle(_translate("VisualiseDialog", "Animation mode"))
        self.canvasAnimation.setToolTip(_translate("VisualiseDialog", "Animation will be shown in map canvas, using sole or currently selected animation file"))
        self.canvasAnimation.setText(_translate("VisualiseDialog", "Map canvas"))
        self.printAnimation.setText(_translate("VisualiseDialog", "Print composer"))
        self.animationSetup.setTitle(_translate("VisualiseDialog", "Set up animation"))
        self.newAnimation.setToolTip(_translate("VisualiseDialog", "Create new animation file"))
        self.newAnimation.setText(_translate("VisualiseDialog", "New"))
        self.currentAnimation.setToolTip(_translate("VisualiseDialog", "<html><head/><body><p>Change sole or currently selected animation file</p></body></html>"))
        self.currentAnimation.setText(_translate("VisualiseDialog", "Current"))
        self.animationVariableCombo.setToolTip(_translate("VisualiseDialog", "Select variable for animation"))
        self.label_2.setText(_translate("VisualiseDialog", "Variable  "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.animationTab), _translate("VisualiseDialog", "Animation"))
        self.observedFileBox.setTitle(_translate("VisualiseDialog", "Choose observed data file (optional)"))
        self.observedFileButton.setText(_translate("VisualiseDialog", "..."))
        self.unitPlot.setToolTip(_translate("VisualiseDialog", "Select a subbasin for the currently selected plot."))
        self.variablePlot.setToolTip(_translate("VisualiseDialog", "Select the current plot\'s variable."))
        self.addPlot.setToolTip(_translate("VisualiseDialog", "Add a plot using the current scenario, ouput table, subbasin, HRU and variables."))
        self.addPlot.setText(_translate("VisualiseDialog", "Add plot"))
        self.deletePlot.setToolTip(_translate("VisualiseDialog", "Delete the currently selected plot."))
        self.deletePlot.setText(_translate("VisualiseDialog", "Delete plot"))
        self.copyPlot.setToolTip(_translate("VisualiseDialog", "Copy the current selected plot."))
        self.copyPlot.setText(_translate("VisualiseDialog", "Copy plot"))
        self.upPlot.setToolTip(_translate("VisualiseDialog", "Move the selected plot up 1 place."))
        self.upPlot.setText(_translate("VisualiseDialog", "Move up"))
        self.downPlot.setToolTip(_translate("VisualiseDialog", "Move the selected plot down 1 place."))
        self.downPlot.setText(_translate("VisualiseDialog", "Move down"))
        self.addObserved.setToolTip(_translate("VisualiseDialog", "Add a plot from the obeserved data file."))
        self.addObserved.setText(_translate("VisualiseDialog", "Add \n"
"observed"))
        self.plotButton.setToolTip(_translate("VisualiseDialog", "Save the data for the plots in the table in a comma-separated values (csv)  file and open SWATGraph on the csv file."))
        self.plotButton.setText(_translate("VisualiseDialog", "Plot"))
        self.unitLabel.setText(_translate("VisualiseDialog", "Unit"))
        self.label_13.setText(_translate("VisualiseDialog", "Variable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VisualiseDialog", "Plot"))
        self.QqSpin.setToolTip(_translate("VisualiseDialog", "<html><head/><body><p>In each month, this percentage of the subbasin\'s outflows will be above the calculated result for the month.</p></body></html>"))
        self.label_17.setText(_translate("VisualiseDialog", "Results"))
        self.label_12.setText(_translate("VisualiseDialog", "Subbasin"))
        self.QqSubbasin.setToolTip(_translate("VisualiseDialog", "Select subbasin.  Watershed outlet is selected initially as default."))
        self.QqCalculate.setText(_translate("VisualiseDialog", "Calculate"))
        self.QqSave.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Save results in text file.  If file exists and Append is ticked, results are apprnded to existing file.</span></p></body></html>"))
        self.QqSave.setText(_translate("VisualiseDialog", "Save"))
        self.QqAppend.setText(_translate("VisualiseDialog", "Append"))
        self.label_11.setText(_translate("VisualiseDialog", "q (percentile: upper bound)"))
        self.QtabWidget.setTabText(self.QtabWidget.indexOf(self.tab_3), _translate("VisualiseDialog", "Qq"))
        self.label_18.setText(_translate("VisualiseDialog", "d (days for moving average)"))
        self.dQpCalculate.setText(_translate("VisualiseDialog", "Calculate"))
        self.dQpSpinP.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This percentage of the subbasins\'s outflows will be below the calculated result.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dQpResult.setText(_translate("VisualiseDialog", "Result:                 "))
        self.label_20.setText(_translate("VisualiseDialog", "Subbasin"))
        self.dQpSubbasin.setToolTip(_translate("VisualiseDialog", "Select subbasin.  Watershed outlet is selected initially as default."))
        self.dQpSave.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Save results in text file.  If file exists and Append is ticked, results are apprnded to existing file.</span></p></body></html>"))
        self.dQpSave.setText(_translate("VisualiseDialog", "Save"))
        self.dQpAppend.setText(_translate("VisualiseDialog", "Append"))
        self.label_21.setText(_translate("VisualiseDialog", "Start month"))
        self.dQpStartMonth.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Result is calculated as mean of figure for each complete year in the chosen period starting at the beginning of  this month.</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("VisualiseDialog", "Final selection"))
        self.dQpPercentile.setText(_translate("VisualiseDialog", "Percentile"))
        self.dQpMean.setText(_translate("VisualiseDialog", "Mean"))
        self.label_19.setText(_translate("VisualiseDialog", "p (percentile: lower bound)"))
        self.QtabWidget.setTabText(self.QtabWidget.indexOf(self.tab_4), _translate("VisualiseDialog", "dQp"))
        self.label_23.setText(_translate("VisualiseDialog", "Subbasin"))
        self.QbAnnualResult.setText(_translate("VisualiseDialog", "Annual result:"))
        self.QbSubbasin.setToolTip(_translate("VisualiseDialog", "Select subbasin.  Watershed outlet is selected initially as default."))
        self.label_22.setText(_translate("VisualiseDialog", "Monthly results"))
        self.label_24.setText(_translate("VisualiseDialog", "Start month"))
        self.QbStartMonth.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Result is calculated as mean of figure for each complete year in the chosen period starting at the beginning of  this month.</span></p></body></html>"))
        self.QbCalculate.setText(_translate("VisualiseDialog", "Calculate"))
        self.QbSave.setToolTip(_translate("VisualiseDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Save results in text file.  If file exists and Append is ticked, results are apprnded to existing file.</span></p></body></html>"))
        self.QbSave.setText(_translate("VisualiseDialog", "Save"))
        self.QbAppend.setText(_translate("VisualiseDialog", "Append"))
        self.QtabWidget.setTabText(self.QtabWidget.indexOf(self.tab_5), _translate("VisualiseDialog", "Qb"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VisualiseDialog", "Post processing"))
        self.closeButton.setText(_translate("VisualiseDialog", "Close"))
        self.periodBox.setTitle(_translate("VisualiseDialog", "Choose period"))
        self.label_4.setToolTip(_translate("VisualiseDialog", "The finish date defaults to the earliest finish date amongst the scenarios chosen, but can be set to an  earlier date by the user."))
        self.label_4.setText(_translate("VisualiseDialog", "Finish date"))
        self.label_5.setText(_translate("VisualiseDialog", "Day"))
        self.label_7.setText(_translate("VisualiseDialog", "Month"))
        self.label_9.setText(_translate("VisualiseDialog", "Year"))
        self.label_6.setText(_translate("VisualiseDialog", "Day"))
        self.label_8.setText(_translate("VisualiseDialog", "Month"))
        self.label_10.setText(_translate("VisualiseDialog", "Year"))
        self.label_3.setToolTip(_translate("VisualiseDialog", "The start date defaults to the latest start date amongst the scenarios chosen, but can be set to a  later date by the user."))
        self.label_3.setText(_translate("VisualiseDialog", "Start date"))

from . import resources_rc
