from peewee import *
from . import base


class Codes_bsn(base.BaseModel):
	pet_file = CharField(null=True)
	wq_file = CharField(null=True)
	pet = IntegerField()
	event = IntegerField()
	crack = IntegerField()
	rtu_wq = IntegerField()
	sed_det = IntegerField()
	rte_cha = IntegerField()
	deg_cha = IntegerField()
	wq_cha = IntegerField()
	rte_pest = IntegerField()
	cn = IntegerField()
	c_fact = IntegerField()
	carbon = IntegerField()
	baseflo = IntegerField()
	uhyd = IntegerField()
	sed_cha = IntegerField()
	tiledrain = IntegerField()
	wtable = IntegerField()
	soil_p = IntegerField()
	abstr_init = IntegerField()
	atmo_dep = CharField()
	stor_max = IntegerField()
	headwater = IntegerField()


class Parameters_bsn(base.BaseModel):
	lai_noevap = DoubleField()
	sw_init = DoubleField()
	surq_lag = DoubleField()
	adj_pkrt = DoubleField()
	adj_pkrt_sed = DoubleField()
	lin_sed = DoubleField()
	exp_sed = DoubleField()
	orgn_min = DoubleField()
	n_uptake = DoubleField()
	p_uptake = DoubleField()
	n_perc = DoubleField()
	p_perc = DoubleField()
	p_soil = DoubleField()
	p_avail = DoubleField()
	rsd_decomp = DoubleField()
	pest_perc = DoubleField()
	msk_co1 = DoubleField()
	msk_co2 = DoubleField()
	msk_x = DoubleField()
	trans_loss = DoubleField()
	evap_adj = DoubleField()
	cn_co = DoubleField()
	denit_exp = DoubleField()
	denit_frac = DoubleField()
	man_bact = DoubleField()
	adj_uhyd = DoubleField()
	cn_froz = DoubleField()
	dorm_hr = DoubleField()
	s_max = DoubleField()
	n_fix = DoubleField()
	n_fix_max = DoubleField()
	rsd_decay = DoubleField()
	rsd_cover = DoubleField()
	vel_crit = DoubleField()
	res_sed = DoubleField()
	uhyd_alpha = DoubleField()
	splash = DoubleField()
	rill = DoubleField()
	surq_exp = DoubleField()
	cov_mgt = DoubleField()
	cha_d50 = DoubleField()
	cha_part_sd = DoubleField()
	adj_cn = DoubleField()
	igen = IntegerField()
